import type { BootStep } from '../types';
import { RAIL_COLORS } from './constants';

/**
 * The coreboot chain, from the first instruction at the reset vector to the
 * jump into GRUB.
 *
 * Everything here happens on hardware that already exists in the scene, so the
 * story is carried by where code and data travel — flash to cache, cache to
 * DRAM, DRAM to payload — while the console panel carries the POST codes and
 * log lines coreboot actually emits.
 */
export const COREBOOT_SEQUENCE_STEPS: BootStep[] = [
  {
    id: 'cb-start',
    phase: 'firmware',
    title: { en: '_start — The 16 Bytes at the Top', tr: '_start — Tepedeki 16 Byte' },
    signal: 'entry16.S:158',
    description: {
      en: 'The linker script places _start at exactly 0xFFFFFFF0, which is where the CPU is already pointing. There are only sixteen bytes left before the address space ends, so this code does one thing: a far jump to the real bootblock. The reset vector is not a door, it is a signpost.',
      tr: 'Linker script _start’ı tam olarak 0xFFFFFFF0’a yerleştirir; CPU zaten oraya bakmaktadır. Adres uzayının sonuna yalnızca on altı byte kalmıştır, bu yüzden bu kod tek bir iş yapar: gerçek bootblock’a bir far jump. Reset vector bir kapı değil, bir tabeladır.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['spiFlash', 'cpuBsp'],
    console: ['0xFFFFFFF0: jmp _start16bit', '[coreboot] bootblock entry'],
    signals: [
      {
        route: ['spiFlash', 'chipset', 'cpuBsp'],
        color: RAIL_COLORS.firmware,
        label: '_start',
        particles: 12,
        spread: 0.6,
      },
    ],
  },
  {
    id: 'cb-16bit',
    phase: 'firmware',
    title: { en: '_start16bit — Into Protected Mode', tr: '_start16bit — Protected Mode’a' },
    signal: 'entry16.S:42',
    description: {
      en: 'Still in 16-bit real mode. First cli, because there is no valid IDT yet and an interrupt now would be fatal. The BIST result the CPU left in EAX is stashed for later diagnostics, the TLB is flushed in case anything survived an S3 resume, and a minimal flat GDT is loaded. Then one bit — CR0.PE — flips the CPU into protected mode.',
      tr: 'Hâlâ 16-bit real mode. Önce cli, çünkü henüz geçerli bir IDT yoktur ve şimdi gelecek bir kesme ölümcül olurdu. CPU’nun EAX’te bıraktığı BIST sonucu sonraki tanılama için saklanır, bir S3 dönüşünden kalıntı olabileceği için TLB temizlenir ve minimal, düz bir GDT yüklenir. Ardından tek bir bit — CR0.PE — CPU’yu protected mode’a geçirir.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuBsp'],
    console: [
      'cli',
      'BIST result = 0x00000000  (passed)',
      'invlpg / TLB flushed',
      'lgdt  -> flat GDT',
      'CR0.PE = 1  -> protected mode',
    ],
    signals: [],
  },
  {
    id: 'cb-32bit',
    phase: 'firmware',
    title: {
      en: 'bootblock_protected_mode_entry',
      tr: 'bootblock_protected_mode_entry',
    },
    signal: 'entry32.S:29',
    description: {
      en: 'Now 32-bit. DS, ES, SS, FS and GS are all pointed at flat segments, making segmentation a formality. CR4 gets its SSE bits set — not for performance but for survival: GCC emits SSE instructions inside things like memcpy, and without OSFXSR that code would fault on an invalid opcode. The TSC is read for the first timestamp, the one that answers "when did the bootblock start".',
      tr: 'Artık 32-bit. DS, ES, SS, FS ve GS’in hepsi düz segmentlere yönlendirilir ve segmentasyon bir formaliteye dönüşür. CR4’ün SSE bitleri açılır — performans için değil, hayatta kalmak için: GCC memcpy gibi yerlerde SSE komutları üretir ve OSFXSR olmadan o kod invalid opcode ile çökerdi. TSC ilk timestamp için okunur; “bootblock ne zaman başladı” sorusunun cevabı budur.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuBsp'],
    console: [
      'ds/es/ss/fs/gs -> flat',
      'CR4.OSFXSR = 1  (SSE enabled)',
      'timestamp: 1  bootblock start',
    ],
    signals: [],
  },
  {
    id: 'cb-car',
    phase: 'firmware',
    title: { en: 'Cache-as-RAM — Memory Before Memory', tr: 'Cache-as-RAM — Bellekten Önceki Bellek' },
    signal: 'SOC_CAR_INIT_DONE',
    description: {
      en: 'C code needs a stack, and DRAM does not exist yet. So the CPU turns its own cache into RAM. The MTRRs are cleared of anything left over, a region is marked write-back cacheable, and the cache is put into no-eviction mode so nothing can ever be flushed out to a memory that is not there. ESP is set inside that region — and from this instant, C functions can be called.',
      tr: 'C kodunun bir stack’e ihtiyacı vardır ve DRAM henüz yoktur. Bu yüzden CPU kendi cache’ini RAM’e dönüştürür. MTRR’lerde kalıntı ne varsa temizlenir, bir bölge write-back cacheable olarak işaretlenir ve cache no-eviction moduna alınır; böylece hiçbir şey var olmayan bir belleğe flush edilemez. ESP bu bölgenin içine kurulur — ve bu andan itibaren C fonksiyonları çağrılabilir.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuBsp', 'cpuCache'],
    console: [
      'POST 0x21  SOC_SET_UP_CAR_MTRRS',
      'MTRR: CAR region write-back',
      'cache: no-eviction mode',
      'esp -> CAR  (stack ready)',
      'POST 0x22  SOC_CAR_INIT_DONE',
    ],
    signals: [
      {
        route: ['cpuBsp', 'cpuCache'],
        color: RAIL_COLORS.data,
        label: 'stack in cache',
        particles: 10,
        persist: true,
        spread: 0.5,
      },
    ],
  },
  {
    id: 'cb-c-entry',
    phase: 'firmware',
    title: { en: 'bootblock_c_entry — First C Function', tr: 'bootblock_c_entry — İlk C Fonksiyonu' },
    signal: { en: 'assembly → C', tr: 'assembly → C' },
    description: {
      en: 'With a stack in place, assembly finally calls into C. The UART is brought up first so there is somewhere to print before CBMEM console exists, and the SPI controller is initialised because the next step has to read from flash. Everything here stays deliberately small — CAR is only a few tens of kilobytes.',
      tr: 'Stack hazır olunca assembly nihayet C’ye çağrı yapar. Önce UART ayağa kaldırılır; böylece CBMEM console var olmadan önce yazılacak bir yer olur. Ardından SPI kontrolcüsü hazırlanır, çünkü bir sonraki adım flash’tan okuyacaktır. Buradaki her şey bilinçli olarak küçük tutulur — CAR yalnızca birkaç on kilobayttır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuBsp', 'superio', 'spiFlash'],
    console: [
      'coreboot-4.22 bootblock starting...',
      'UART 0x3f8 initialised @ 115200',
      'SPI controller ready',
    ],
    signals: [
      {
        route: ['cpuBsp', 'superio'],
        color: RAIL_COLORS.data,
        label: 'UART console',
        particles: 8,
        spread: 0.4,
      },
      {
        route: ['cpuBsp', 'chipset', 'spiFlash'],
        color: RAIL_COLORS.firmware,
        particles: 8,
        delay: 0.4,
        spread: 0.4,
      },
    ],
  },
  {
    id: 'cb-romstage-load',
    phase: 'firmware',
    title: { en: 'run_romstage() — Loading From CBFS', tr: 'run_romstage() — CBFS’ten Yükleme' },
    signal: 'prog_loaders.c:18',
    description: {
      en: 'CBFS is coreboot\'s filesystem on the flash: a simple index that finds a named blob and hands it back. romstage is located, decompressed with LZMA if it was stored compressed, and executed through prog_run(). On some platforms romstage is linked into the bootblock instead and simply called.',
      tr: 'CBFS, coreboot’un flash üzerindeki dosya sistemidir: isimle bir blob bulup geri veren basit bir indeks. romstage bulunur, sıkıştırılmış saklandıysa LZMA ile açılır ve prog_run() üzerinden çalıştırılır. Bazı platformlarda romstage bootblock’a linklenmiştir ve doğrudan çağrılır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['spiFlash', 'chipset', 'cpuCache'],
    console: [
      'CBFS: found "fallback/romstage"',
      'CBFS: decompressing LZMA 48 KiB',
      'Jumping to romstage.',
    ],
    signals: [
      {
        route: ['spiFlash', 'chipset', 'cpuCache'],
        color: RAIL_COLORS.firmware,
        label: 'romstage',
        particles: 12,
        spread: 0.6,
      },
    ],
  },
  {
    id: 'cb-ram-training',
    phase: 'firmware',
    title: { en: 'romstage_main() — RAM Training', tr: 'romstage_main() — RAM Training' },
    signal: 'MEM_PREINIT_PREP',
    description: {
      en: 'The big one. SPD data is read from each DIMM over SMBus, the memory controller is configured, and write, read and command training run until the timings actually work at speed — usually inside an FSP-M or AGESA blob. At the end of this step the machine has real, usable DRAM for the first time in its life.',
      tr: 'Büyük olan bu. Her DIMM’den SMBus üzerinden SPD verisi okunur, bellek denetleyicisi yapılandırılır ve write, read ve command training zamanlamalar hızda gerçekten çalışana kadar sürer — genelde bir FSP-M ya da AGESA blob’unun içinde. Bu adımın sonunda makine hayatında ilk kez gerçek, kullanılabilir DRAM’e sahiptir.',
    },
    duration: 6400,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: [
      'POST 0x34  MEM_PREINIT_PREP_START',
      'SPD: DIMM0 8192 MB DDR4-3200',
      'SPD: DIMM1 8192 MB DDR4-3200',
      'FSP-M: write leveling ... ok',
      'FSP-M: read training  ... ok',
      'POST 0x36  MEM_PREINIT_PREP_END',
    ],
    signals: [
      {
        route: ['cpuBsp', 'ram'],
        color: RAIL_COLORS.data,
        label: 'memory training',
        particles: 16,
        persist: true,
        thickness: 1.2,
      },
    ],
  },
  {
    id: 'cb-ramstage',
    phase: 'firmware',
    title: { en: 'run_ramstage() — Moving Into DRAM', tr: 'run_ramstage() — DRAM’e Taşınma' },
    signal: 'RAMSTAGE_IS_PREPARED',
    description: {
      en: 'The delicate moment. The stack living in cache has to be migrated to a real stack in DRAM, and only then can CAR be torn down and the cache returned to behaving like a cache. Ramstage — larger than romstage, usually LZMA compressed in CBFS — is loaded into that new DRAM and run.',
      tr: 'Hassas an. Cache’te yaşayan stack DRAM’deki gerçek bir stack’e taşınmak zorundadır ve ancak ondan sonra CAR sökülüp cache yeniden cache gibi davranmaya döndürülebilir. romstage’den büyük ve CBFS’te genelde LZMA ile sıkıştırılmış duran ramstage, bu yeni DRAM’e yüklenip çalıştırılır.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['cpuCache', 'ram', 'spiFlash'],
    console: [
      'POST 0x4a  PREPARE_RAMSTAGE',
      'stack migrated CAR -> DRAM',
      'CAR torn down, cache back to normal',
      'CBFS: found "fallback/ramstage"',
      'POST 0x4b  RAMSTAGE_IS_PREPARED',
    ],
    signals: [
      {
        route: ['cpuCache', 'ram'],
        color: RAIL_COLORS.kernel,
        label: 'stack migration',
        particles: 12,
        spread: 0.4,
      },
      {
        route: ['spiFlash', 'chipset', 'ram'],
        color: RAIL_COLORS.firmware,
        label: 'ramstage',
        particles: 10,
        delay: 0.42,
        spread: 0.45,
        persist: true,
      },
    ],
  },
  {
    id: 'cb-hardwaremain',
    phase: 'firmware',
    title: { en: 'main() — Ramstage Begins', tr: 'main() — Ramstage Başlıyor' },
    signal: 'hardwaremain.c:426',
    description: {
      en: 'console_init() brings up the full logging system, CBMEM console included — on a cold boot CBMEM is created from scratch, on an S3 resume the previous session\'s contents are validated and reused. boot_state_schedule_static_entries() then registers which functions run at which stage of the state machine that follows.',
      tr: 'console_init() CBMEM console dahil tam log sistemini ayağa kaldırır — soğuk açılışta CBMEM sıfırdan oluşturulur, S3 dönüşünde önceki oturumun içeriği doğrulanıp yeniden kullanılır. Ardından boot_state_schedule_static_entries(), gelecek durum makinesinin hangi aşamasında hangi fonksiyonların çalışacağını kaydeder.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'off',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'POST 0x80  CONSOLE_READY',
      'CBMEM: created @ 0x7fffe000',
      'POST 0x6f  ENTRY_HARDWAREMAIN',
    ],
    signals: [],
  },
  {
    id: 'cb-state-machine',
    phase: 'firmware',
    title: {
      en: 'bs_walk_state_machine() — Bringing Up Devices',
      tr: 'bs_walk_state_machine() — Cihazları Ayağa Kaldırma',
    },
    signal: 'BS_DEV_*',
    description: {
      en: 'The backbone of hardware initialisation, walked one state at a time: chip-specific early init, then PCI enumeration discovering what is actually plugged in, then resources assigned to each device, then enable, then each device\'s own init. BS_WRITE_TABLES finally builds the ACPI, SMBIOS and coreboot tables in RAM — the data structures the payload and the OS will read to understand this machine.',
      tr: 'Donanım initialization’ının omurgası, her seferinde bir durum ilerletilerek yürütülür: yongaya özel erken init, ardından gerçekte neyin takılı olduğunu keşfeden PCI enumeration, ardından her cihaza kaynak atanması, etkinleştirme ve her cihazın kendi init’i. BS_WRITE_TABLES sonunda ACPI, SMBIOS ve coreboot tablolarını RAM’de oluşturur — payload’ın ve işletim sisteminin bu makineyi anlamak için okuyacağı veri yapıları.',
    },
    duration: 6400,
    view: 'coreboot',
    screen: 'post',
    depth: 1,
    highlight: ['chipset', 'pcie', 'm2', 'ram'],
    console: [
      'POST 0x71  BS_DEV_ENUMERATE',
      'PCI: 00:02.0 VGA compatible controller',
      'PCI: 02:00.0 Non-Volatile memory controller',
      'POST 0x72  BS_DEV_RESOURCES',
      'POST 0x74  BS_DEV_INIT',
      'POST 0x76  BS_WRITE_TABLES',
      'ACPI: DSDT, FADT, MADT written',
    ],
    signals: [
      {
        route: ['chipset', 'pcie'],
        color: RAIL_COLORS.data,
        label: 'PCI enumeration',
        particles: 8,
        spread: 0.32,
      },
      {
        route: ['chipset', 'm2'],
        color: RAIL_COLORS.data,
        particles: 8,
        delay: 0.22,
        spread: 0.32,
      },
      {
        route: ['chipset', 'ram'],
        color: RAIL_COLORS.kernel,
        label: 'ACPI tables',
        particles: 10,
        delay: 0.5,
        spread: 0.38,
        persist: true,
      },
    ],
  },
  {
    id: 'cb-payload-load',
    phase: 'firmware',
    title: { en: 'bs_payload_load — Fetching GRUB', tr: 'bs_payload_load — GRUB’ı Getirme' },
    signal: 'BS_PAYLOAD_LOAD',
    description: {
      en: 'payload_load() finds the payload in CBFS and reads it into memory, decompressing if needed. On this machine that payload is GRUB — coreboot itself has no interest in filesystems or kernels, it just needs something to hand control to.',
      tr: 'payload_load() payload’ı CBFS’te bulup belleğe okur, gerekiyorsa açar. Bu makinede o payload GRUB’dır — coreboot’un dosya sistemleriyle ya da kernel’lerle hiçbir işi yoktur, yalnızca kontrolü devredeceği bir şeye ihtiyacı vardır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'post',
    depth: 1,
    highlight: ['spiFlash', 'ram'],
    console: [
      'POST 0x77  BS_PAYLOAD_LOAD',
      'CBFS: found "fallback/payload"',
      'Loading segment 0x00100000 (412 KiB)',
    ],
    signals: [
      {
        route: ['spiFlash', 'chipset', 'ram'],
        color: RAIL_COLORS.firmware,
        label: 'GRUB payload',
        particles: 12,
        spread: 0.6,
        persist: true,
      },
    ],
  },
  {
    id: 'cb-payload-run',
    phase: 'firmware',
    title: { en: 'payload_run() — The Last Instruction', tr: 'payload_run() — Son Komut' },
    signal: 'prog_loaders.c:188',
    description: {
      en: 'boot_successful() records that the machine got this far, which on some platforms clears a failed-boot counter feeding the fallback and recovery logic. Then prog_run() jumps to the payload entry point. This is coreboot\'s final instruction: not a call, a jump. There is no return.',
      tr: 'boot_successful(), makinenin buraya kadar geldiğini kaydeder; bazı platformlarda bu, fallback ve kurtarma mantığını besleyen bir “önceki boot başarısız” sayacını sıfırlar. Ardından prog_run() payload’ın giriş noktasına atlar. Bu, coreboot’un son komutudur: bir çağrı değil, bir jump. Geri dönüş yoktur.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'post',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'POST 0x78  BS_PAYLOAD_BOOT',
      'boot_successful()',
      'Jumping to boot code at 0x00100000',
    ],
    signals: [
      {
        route: ['ram', 'cpuBsp'],
        color: RAIL_COLORS.kernel,
        label: 'jmp payload',
        particles: 14,
        spread: 0.6,
        persist: true,
      },
    ],
  },
  {
    id: 'cb-grub',
    phase: 'firmware',
    title: { en: 'grub_main() — No Longer coreboot', tr: 'grub_main() — Artık coreboot Değil' },
    signal: 'kern/main.c',
    description: {
      en: 'Control belongs entirely to GRUB now. coreboot\'s POST code system goes quiet and GRUB starts printing through its own console. coreboot\'s job is finished — kernel selection, initramfs loading and the handoff to Linux are all somebody else\'s problem from here.',
      tr: 'Kontrol tamamen GRUB’ındır. coreboot’un POST kodu sistemi susar ve GRUB kendi konsolundan yazmaya başlar. coreboot’un işi bitmiştir — kernel seçimi, initramfs yükleme ve Linux’a devir buradan sonra başkasının meselesidir.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['Welcome to GRUB!', 'grub_main(): console handed over'],
    signals: [],
  },
  {
    id: 'cb-smm',
    phase: 'firmware',
    title: { en: 'SMM — The Part That Never Leaves', tr: 'SMM — Hiç Gitmeyen Kısım' },
    signal: 'SMI → SMRAM',
    description: {
      en: 'One thing coreboot leaves behind. During ramstage it installed handlers into SMRAM, a region hidden from the operating system, running in System Management Mode — a privilege level above ring 0 that neither GRUB nor Linux can see or intercept. Certain hardware events raise an SMI: the CPU saves its entire state, runs coreboot\'s handler, and returns with RSM as if nothing happened.',
      tr: 'coreboot’un geride bıraktığı tek şey. Ramstage sırasında, işletim sisteminden gizlenmiş bir bölge olan SMRAM’e handler’lar kurmuştu; bunlar System Management Mode’da çalışır — ring 0’ın da üstünde, ne GRUB’ın ne de Linux’un görebildiği ya da araya girebildiği bir ayrıcalık seviyesi. Belirli donanım olayları bir SMI yükseltir: CPU tüm durumunu kaydeder, coreboot’un handler’ını çalıştırır ve RSM ile hiçbir şey olmamış gibi geri döner.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram', 'chipset'],
    console: [
      'SMM: installing handler into SMRAM',
      'SMI sources: PWRBTN, thermal, legacy USB',
      '-- later, while Linux runs --',
      'SMI# -> state saved -> handler -> RSM',
    ],
    signals: [
      {
        route: ['chipset', 'cpuBsp'],
        color: RAIL_COLORS.logic,
        label: 'SMI#',
        particles: 8,
        spread: 0.4,
      },
      {
        route: ['cpuBsp', 'ram'],
        color: RAIL_COLORS.logic,
        label: 'SMRAM',
        particles: 8,
        delay: 0.4,
        spread: 0.4,
      },
    ],
  },
];
