import type { BootStep } from '../types';
import { RAIL_COLORS } from './constants';

/**
 * From coreboot's jump into GRUB to Linux reaching start_kernel().
 *
 * All software, but not all abstract: the kernel really does travel from the
 * M.2 into DRAM, the framebuffer really is handed over, and the two one-way
 * jumps that end GRUB and end the decompression stub are the spine of the
 * story. The console panel carries what each stage prints or checks.
 *
 * Reuses the 'coreboot' framing — the same components are on stage.
 */
const FW = RAIL_COLORS.firmware;
const DATA = RAIL_COLORS.data;
const KERNEL = RAIL_COLORS.kernel;

export const GRUB_SEQUENCE_STEPS: BootStep[] = [
  {
    id: 'grub-start',
    phase: 'os',
    title: { en: '_start — Multiboot Handshake', tr: '_start — Multiboot El Sıkışması' },
    signal: 'startup.S',
    source: 'grub-core/kern/i386/coreboot/startup.S:37',
    description: {
      en: "coreboot's jump lands here. GRUB's first act is to check the Multiboot magic number — the standard handshake between a firmware and a payload — confirming it really was started in an environment it understands. Then it builds its own stack: coreboot's is no longer valid, and GRUB needs ground of its own to stand on.",
      tr: 'coreboot’un jump’ı buraya düşer. GRUB’ın ilk işi Multiboot magic sayısını denetlemektir — bir firmware ile bir payload arasındaki standart el sıkışma — böylece gerçekten anladığı bir ortamda başlatıldığını doğrular. Ardından kendi stack’ini kurar: coreboot’unki artık geçerli değildir ve GRUB’ın basacağı kendi zeminine ihtiyacı vardır.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['Multiboot magic 0x2BADB002  ok', 'GRUB stack established'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: FW, label: 'jmp grub_main', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'grub-main',
    phase: 'os',
    title: { en: 'grub_main() — GRUB in C', tr: 'grub_main() — C Dünyasında GRUB' },
    signal: 'kern/main.c',
    source: 'grub-core/kern/main.c:304',
    description: {
      en: "The real entry point of GRUB's C world. From here it proceeds entirely on its own architecture, owing nothing further to coreboot's structure.",
      tr: 'GRUB’ın C dünyasındaki gerçek giriş noktası. Buradan itibaren tamamen kendi mimarisiyle ilerler; coreboot’un yapısına artık hiçbir borcu yoktur.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['grub_main() entered'],
    signals: [],
  },
  {
    id: 'grub-machine-init',
    phase: 'os',
    title: { en: 'grub_machine_init()', tr: 'grub_machine_init()' },
    signal: { en: 'platform bring-up', tr: 'platform hazırlığı' },
    source: 'grub-core/kern/i386/coreboot/init.c:94',
    description: {
      en: 'Platform-specific setup for the coreboot target: the VGA or framebuffer console so a menu can be drawn at all, a heap so GRUB has dynamic memory of its own, and the TSC for timing.',
      tr: 'coreboot hedefine özel kurulum: menünün çizilebilmesi için VGA ya da framebuffer konsolu, GRUB’ın kendi dinamik belleği için bir heap ve zamanlama için TSC.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['pcie', 'ram', 'cpuBsp'],
    console: ['video: framebuffer 1920x1080x32', 'heap initialised', 'TSC calibrated'],
    signals: [
      { route: ['cpuBsp', 'pcie'], color: DATA, label: 'framebuffer', particles: 8, spread: 0.4 },
      { route: ['cpuBsp', 'ram'], color: DATA, label: 'heap', particles: 8, delay: 0.4, spread: 0.4 },
    ],
  },
  {
    id: 'grub-cbtable',
    phase: 'os',
    title: { en: 'Reading the coreboot Table', tr: 'coreboot Tablosunu Okuma' },
    signal: 'cbtable.c',
    source: 'grub-core/kern/i386/coreboot/cbtable.c:29',
    description: {
      en: 'Back in ramstage, BS_WRITE_TABLES left a coreboot table in memory holding everything the firmware had learned — the memory map, where the CBMEM console lives, board identity. GRUB scans memory, finds it and reads it, inheriting all of that rather than rediscovering the hardware itself.',
      tr: 'Ramstage’de BS_WRITE_TABLES, firmware’in öğrendiği her şeyi tutan bir coreboot table’ı bellekte bırakmıştı — bellek haritası, CBMEM console’un yeri, kart kimliği. GRUB belleği tarar, onu bulur ve okur; donanımı yeniden keşfetmek yerine bunların hepsini devralır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'coreboot table found @ 0x00000500',
      'CB_TAG_MEMORY: 5 ranges',
      'CB_TAG_CBMEM_CONSOLE inherited',
    ],
    signals: [
      { route: ['ram', 'cpuBsp'], color: DATA, label: 'coreboot table', particles: 10, spread: 0.5 },
    ],
  },
  {
    id: 'grub-config',
    phase: 'os',
    title: { en: 'grub.cfg — The Menu Runs', tr: 'grub.cfg — Menü Çalışıyor' },
    signal: 'normal mode',
    source: 'grub-core/kern/main.c:233',
    description: {
      en: 'grub.cfg is read and normal mode starts. From here GRUB is simply executing the commands you wrote — linux, initrd, boot — one after another.',
      tr: 'grub.cfg okunur ve normal mode başlar. Buradan itibaren GRUB yalnızca senin yazdığın komutları — linux, initrd, boot — sırayla işletiyordur.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'ram'],
    console: ['loading grub.cfg', 'menuentry "Linux" selected'],
    signals: [
      { route: ['m2', 'chipset', 'ram'], color: FW, label: 'grub.cfg', particles: 8, spread: 0.6 },
    ],
  },
  {
    id: 'grub-cmd-linux',
    phase: 'os',
    title: { en: 'linux /vmlinuz — Opening the bzImage', tr: 'linux /vmlinuz — bzImage Açılıyor' },
    signal: 'grub_cmd_linux()',
    source: 'grub-core/loader/i386/linux.c:675',
    description: {
      en: 'The kernel file is opened and its header read. That header carries everything a bootloader needs to know about the kernel it is about to place: sizes, version, which features it supports.',
      tr: 'Kernel dosyası açılır ve header’ı okunur. Bu header, bir bootloader’ın yerleştirmek üzere olduğu kernel hakkında bilmesi gereken her şeyi taşır: boyutlar, sürüm, desteklediği özellikler.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'ram'],
    console: ['open (hd0,gpt2)/vmlinuz-6.11.0', 'reading setup header (0x1f1)'],
    signals: [
      { route: ['m2', 'ram'], color: DATA, label: 'linux header', particles: 10, spread: 0.5 },
    ],
  },
  {
    id: 'grub-validate',
    phase: 'os',
    title: { en: 'Validation — Four Checks', tr: 'Doğrulama — Dört Kontrol' },
    signal: '"HdrS" · 0xaa55',
    description: {
      en: 'boot_flag must be 0xaa55, the ancient MBR boot-sector signature the bzImage format still carries because it descends from it. The "HdrS" magic confirms this really is a Linux kernel. The protocol version must be at least 0x0203 so the fields GRUB intends to use are understood on the other side. And BIG_KERNEL says the image is too large for the old low-memory path, so the modern protected-mode route is required.',
      tr: 'boot_flag 0xaa55 olmalıdır — bzImage formatının ondan türediği için hâlâ taşıdığı kadim MBR boot sektörü imzası. "HdrS" magic’i bunun gerçekten bir Linux kernel’i olduğunu doğrular. Protokol sürümü en az 0x0203 olmalıdır ki GRUB’ın kullanacağı alanlar öbür tarafta da anlaşılsın. BIG_KERNEL ise imajın eski düşük bellek yoluna sığmayacak kadar büyük olduğunu, yani modern protected-mode yolunun gerektiğini söyler.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: [
      'boot_flag   = 0xaa55     ok',
      'header      = "HdrS"     ok',
      'version     = 0x020f     >= 0x0203',
      'loadflags   = BIG_KERNEL',
    ],
    signals: [],
  },
  {
    id: 'grub-sizes',
    phase: 'os',
    title: { en: 'Sizes and Relocatability', tr: 'Boyutlar ve Yeniden Konumlanabilirlik' },
    signal: 'real_size · prot_size',
    description: {
      en: 'real_size is the small 16-bit setup stub at the front of the image; prot_size is the actual compressed kernel that will be loaded in protected mode. The header also declares whether the kernel is relocatable and what alignment it demands — the flexibility that KASLR is built on.',
      tr: 'real_size, imajın önündeki küçük 16-bit setup parçasıdır; prot_size ise protected mode’da yüklenecek asıl sıkıştırılmış kernel’dir. Header ayrıca kernel’in yeniden konumlanabilir olup olmadığını ve hangi hizalamayı istediğini bildirir — KASLR’ın üzerine kurulduğu esneklik budur.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: [
      'real_size   = 0x4000   (16 KiB setup)',
      'prot_size   = 0xb42000 (11.2 MiB)',
      'relocatable = 1, align = 0x200000',
    ],
    signals: [],
  },
  {
    id: 'grub-allocate',
    phase: 'os',
    title: { en: 'allocate_pages() — The Relocator', tr: 'allocate_pages() — Relocator' },
    signal: 'grub_relocator_new',
    source: 'grub-core/loader/i386/linux.c:148',
    description: {
      en: "GRUB's relocator is asked for memory at a preferred address. If the map says that region is taken or absent, it relaxes the alignment constraint step by step and tries again — which is what lets the same bootloader place a kernel across wildly different memory layouts.",
      tr: 'GRUB’ın relocator’ından tercih edilen bir adreste bellek istenir. Harita o bölgenin dolu ya da mevcut olmadığını söylüyorsa, hizalama kısıtını kademe kademe gevşetip tekrar dener — aynı bootloader’ın birbirinden çok farklı bellek yerleşimlerinde kernel yerleştirebilmesini sağlayan şey budur.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: [
      'relocator: request 0x1000000 @ align 0x200000',
      'relocator: granted prot_mode_target = 0x1000000',
    ],
    signals: [
      { route: ['cpuBsp', 'ram'], color: DATA, label: 'reserve', particles: 8, spread: 0.5 },
    ],
  },
  {
    id: 'grub-code32',
    phase: 'os',
    title: { en: 'code32_start — Fixing the Address', tr: 'code32_start — Adresin Düzeltilmesi' },
    signal: 'relocation offset',
    description: {
      en: "The header is copied into GRUB's linux_params, and the kernel's real entry address is computed: prot_mode_target + lh.code32_start - BZIMAGE_ADDR. That subtraction is the whole trick — it corrects for the difference between where the kernel was linked to run and where GRUB actually put it.",
      tr: 'Header, GRUB’ın linux_params yapısına kopyalanır ve kernel’in gerçek giriş adresi hesaplanır: prot_mode_target + lh.code32_start − BZIMAGE_ADDR. Bütün numara o çıkarmadadır — kernel’in çalışmak üzere linklendiği adres ile GRUB’ın onu gerçekte koyduğu adres arasındaki farkı düzeltir.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'lh.code32_start  = 0x00100000',
      'prot_mode_target = 0x01000000',
      'code32_start     = 0x01000000',
    ],
    signals: [],
  },
  {
    id: 'grub-read-kernel',
    phase: 'os',
    title: { en: 'Reading the Kernel Into Memory', tr: 'Kernel Belleğe Okunuyor' },
    signal: 'prot_file_size',
    description: {
      en: 'The boot sector and setup code at the front of the file are seeked past — GRUB has no use for them, it is doing the loading itself. The compressed kernel behind them is read straight into the region just reserved.',
      tr: 'Dosyanın önündeki boot sektörü ve setup kodu atlanır — GRUB’ın onlara ihtiyacı yoktur, yüklemeyi kendisi yapmaktadır. Arkalarındaki sıkıştırılmış kernel doğrudan az önce ayrılan bölgeye okunur.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'chipset', 'ram'],
    console: ['seek 0x4000', 'read 11.2 MiB -> 0x01000000'],
    signals: [
      {
        route: ['m2', 'chipset', 'ram'],
        color: FW,
        label: 'vmlinuz',
        particles: 16,
        spread: 0.7,
        persist: true,
        thickness: 1.2,
      },
    ],
  },
  {
    id: 'grub-initrd',
    phase: 'os',
    title: { en: 'initrd — Loaded High on Purpose', tr: 'initrd — Bilerek Yükseğe' },
    signal: 'PREFERENCE_HIGH',
    source: 'grub-core/loader/i386/linux.c:1065',
    description: {
      en: 'The header declares initrd_addr_max, the highest physical address at which the kernel can still find a ramdisk. GRUB asks the relocator for memory with a HIGH preference, deliberately placing the initrd as high as it can — clear of the space the kernel will need as it decompresses downward. Then ramdisk_image and ramdisk_size go into the header, which is exactly where the kernel will look.',
      tr: 'Header, kernel’in bir ramdisk’i hâlâ bulabileceği en yüksek fiziksel adres olan initrd_addr_max’i bildirir. GRUB relocator’dan HIGH tercihiyle bellek ister ve initrd’yi bilinçli olarak olabildiğince yükseğe koyar — kernel açılırken aşağı doğru büyürken ihtiyaç duyacağı alandan uzağa. Ardından ramdisk_image ve ramdisk_size header’a yazılır; kernel tam da oraya bakacaktır.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'ram'],
    console: [
      'initrd_addr_max = 0x7fffffff',
      'relocator HIGH -> 0x7d200000',
      'read initrd 42 MiB',
      'hdr.ramdisk_image = 0x7d200000',
    ],
    signals: [
      {
        route: ['m2', 'chipset', 'ram'],
        color: DATA,
        label: 'initrd',
        particles: 14,
        spread: 0.7,
        persist: true,
      },
    ],
  },
  {
    id: 'grub-boot',
    phase: 'os',
    title: { en: 'boot — screen_info Handover', tr: 'boot — screen_info Devri' },
    signal: 'grub_linux_boot()',
    source: 'grub-core/loader/i386/linux.c:418',
    description: {
      en: 'The handover proper begins. screen_info is filled in with the current video mode — resolution, framebuffer address — so the kernel can carry on drawing where GRUB left off instead of blanking the display.',
      tr: 'Asıl devir başlar. screen_info mevcut video moduyla doldurulur — çözünürlük, framebuffer adresi — böylece kernel ekranı karartmak yerine GRUB’ın bıraktığı yerden çizmeye devam edebilir.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['pcie', 'ram'],
    console: ['screen_info: 1920x1080x32 @ 0xc0000000'],
    signals: [
      { route: ['pcie', 'ram'], color: DATA, label: 'screen_info', particles: 8, spread: 0.5 },
    ],
  },
  {
    id: 'grub-zero-page',
    phase: 'os',
    title: { en: 'The Zero Page', tr: 'Zero Page' },
    signal: 'boot_params',
    description: {
      en: 'Zero page is a historical name: in the old protocol this structure sat at physical address 0. It no longer does, but the name stuck. It is the main handover structure — header plus hardware information. A free region is found, and linux_params and the kernel command line (root=, console=, all of it) are copied there.',
      tr: 'Zero page tarihsel bir isimdir: eski protokolde bu yapı fiziksel adres 0’da dururdu. Artık durmuyor ama isim kaldı. Asıl devir yapısıdır — header artı donanım bilgisi. Boş bir bölge bulunur ve linux_params ile kernel komut satırı (root=, console=, hepsi) oraya kopyalanır.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: [
      'real_mode_target = 0x00090000',
      'copy linux_params (4 KiB)',
      'cmdline: root=/dev/nvme0n1p2 rw quiet',
    ],
    signals: [
      { route: ['cpuBsp', 'ram'], color: KERNEL, label: 'boot_params', particles: 10, spread: 0.5 },
    ],
  },
  {
    id: 'grub-e820',
    phase: 'os',
    title: { en: 'The E820 Memory Map', tr: 'E820 Bellek Haritası' },
    signal: 'e820_entries',
    description: {
      en: 'E820 is the standard map the firmware hands the operating system: which physical ranges are usable RAM, which are reserved, which hold ACPI data. Without it the kernel would have no idea which memory it may safely touch — and writing into a range that belongs to hardware takes the machine down. GRUB fills it in from what coreboot told it.',
      tr: 'E820, firmware’in işletim sistemine verdiği standart haritadır: hangi fiziksel aralıklar kullanılabilir RAM, hangileri ayrılmış, hangileri ACPI verisi tutuyor. O olmadan kernel hangi belleğe güvenle dokunabileceğini bilemezdi — ve donanıma ait bir aralığa yazmak makineyi düşürür. GRUB bunu coreboot’un söylediklerinden doldurur.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'chipset'],
    console: [
      'e820: 0x000000000-0x00009fbff usable',
      'e820: 0x000100000-0x07f5fffff usable',
      'e820: 0x07f600000-0x07f7fffff ACPI data',
      'e820: 0x0fed00000-0x0fed00fff reserved',
      'e820_entries = 9',
    ],
    signals: [
      { route: ['chipset', 'ram'], color: KERNEL, label: 'E820', particles: 10, spread: 0.55 },
    ],
  },
  {
    id: 'grub-registers',
    phase: 'os',
    title: { en: 'The Registers the Kernel Demands', tr: 'Kernel’in Şart Koştuğu Register’lar' },
    signal: 'esi = boot_params',
    description: {
      en: "Linux's 32-bit entry protocol does not merely suggest a register state, it requires one. esi must hold real_mode_target — the address of boot_params — because that register is the only way the kernel learns where its configuration lives. eip is code32_start, the address computed earlier.",
      tr: 'Linux’un 32-bit giriş protokolü bir register durumunu önermez, şart koşar. esi, real_mode_target’ı — boot_params’ın adresini — tutmalıdır; çünkü kernel’in konfigürasyonunun nerede olduğunu öğrenmesinin tek yolu o register’dır. eip ise daha önce hesaplanan code32_start’tır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['esi = 0x00090000  (boot_params)', 'eip = 0x01000000  (code32_start)'],
    signals: [],
  },
  {
    id: 'grub-relocator32',
    phase: 'os',
    title: { en: 'relocator32.S — Back to a Clean Machine', tr: 'relocator32.S — Temiz Makineye Dönüş' },
    signal: { en: 'GDT · paging off', tr: 'GDT · paging kapalı' },
    source: 'grub-core/lib/i386/relocator32.S:29',
    description: {
      en: 'A fresh GDT is loaded so the kernel starts from known segment definitions rather than whatever GRUB happened to be using. Then paging, PAE and long mode are all switched off: the 32-bit entry protocol expects a clean, flat, unpaged protected mode, so GRUB deliberately unwinds everything it had turned on.',
      tr: 'Kernel’in, GRUB’ın o an ne kullanıyorsa ondan değil bilinen segment tanımlarından başlaması için taze bir GDT yüklenir. Ardından paging, PAE ve long mode kapatılır: 32-bit giriş protokolü temiz, düz ve paging’siz bir protected mode bekler, bu yüzden GRUB açtığı her şeyi bilinçli olarak geri sarar.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['lgdt   -> clean GDT', 'CR0.PG = 0', 'CR4.PAE = 0', 'EFER.LME = 0'],
    signals: [],
  },
  {
    id: 'grub-far-jump',
    phase: 'os',
    title: { en: '0xEA — GRUB’s Last Instruction', tr: '0xEA — GRUB’ın Son Komutu' },
    signal: 'far jump',
    source: 'grub-core/lib/i386/relocator32.S',
    description: {
      en: 'Every register is loaded with the value the kernel expects, and then a raw 0xEA far jump throws the CPU at code32_start with nothing in between. This is GRUB\'s final instruction — one-way, exactly like coreboot\'s jump into GRUB was.',
      tr: 'Her register kernel’in beklediği değerle doldurulur ve ardından ham bir 0xEA far jump, CPU’yu araya hiçbir şey girmeden code32_start’a fırlatır. Bu, GRUB’ın son komutudur — tıpkı coreboot’un GRUB’a atlaması gibi tek yönlü.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['0xEA  jmp far 0x01000000', '-- GRUB is done --'],
    signals: [
      {
        route: ['cpuBsp', 'ram'],
        color: KERNEL,
        label: 'jmp code32_start',
        particles: 16,
        spread: 0.7,
        persist: true,
        thickness: 1.2,
      },
    ],
  },
];
