import type { BootStep } from '../types';
import { RAIL_COLORS } from './constants';

/**
 * From GRUB's far jump into startup_32 to the sysretq that starts PID 1.
 *
 * The reader is assumed not to be a kernel developer. Every card opens in plain
 * language and only then names the term, so the vocabulary is earned rather
 * than presumed; the glossary behind the Kernel section carries the full
 * definitions. What a card must always answer is why a step happens where it
 * does — the order is the story, and the order is never arbitrary.
 *
 * Reuses the 'coreboot' framing: the CPU, DRAM and the M.2 are already on
 * stage, and they are the only hardware this chain actually touches. The two
 * driver cards climb back out to the board, where the devices being probed are.
 *
 * Source paths were verified against ~/Projects/linux-master (7.2.0-rc6). Only
 * cards that are genuinely a function or an entry symbol carry one.
 */
const FW = RAIL_COLORS.firmware;
const DATA = RAIL_COLORS.data;
const KERNEL = RAIL_COLORS.kernel;
const LOGIC = RAIL_COLORS.logic;

export const KERNEL_SEQUENCE_STEPS: BootStep[] = [
  // --- Decompressor: 32-bit entry --------------------------------------------
  {
    id: 'kernel-startup32',
    phase: 'os',
    title: { en: 'startup_32 — Where GRUB Let Go', tr: 'startup_32 — GRUB’ın Bıraktığı Yer' },
    signal: 'startup_32',
    source: 'arch/x86/boot/compressed/head_64.S:82',
    description: {
      en: "GRUB's far jump lands here, and nothing of GRUB survives it. What arrives is not the kernel yet — it is a small program whose entire job is to unpack the kernel, wedged into the front of the same file. The CPU is in 32-bit mode with memory translation switched off, exactly as the boot protocol demanded, and %esi holds the address of the table GRUB filled in. That table is now the only thing the kernel knows about the machine.",
      tr: 'GRUB’ın far jump’ı buraya düşer ve GRUB’dan geriye hiçbir şey kalmaz. Buraya varan şey henüz kernel değildir — aynı dosyanın önüne sıkıştırılmış, tek işi kernel’i paketinden çıkarmak olan küçük bir programdır. CPU 32-bit modda ve bellek çevirisi kapalıdır, boot protokolünün şart koştuğu gibi; %esi ise GRUB’ın doldurduğu tablonun adresini tutar. O tablo, kernel’in makine hakkında bildiği tek şeydir artık.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['jmp 0x100000  (code32_start)', 'esi = 0x0009c000  boot_params'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: FW, label: 'code32_start', particles: 14, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-pic',
    phase: 'os',
    title: { en: 'Finding Out Where It Is', tr: 'Nerede Olduğunu Bulmak' },
    signal: 'call 1f / pop %ebp',
    description: {
      en: "This code has a problem most programs never face: it does not know its own address. GRUB was free to load it anywhere, so any address baked in at compile time would be wrong. The trick is three instructions long — call the very next line, then pop the return address off the stack. The CPU pushed the true running address, so the code has just asked the processor where it is. Everything from here uses offsets from that answer.",
      tr: 'Bu kodun, çoğu programın hiç karşılaşmadığı bir sorunu vardır: kendi adresini bilmez. GRUB onu istediği yere yükleyebilirdi, dolayısıyla derleme anında gömülen herhangi bir adres yanlış olurdu. Numara üç talimat uzunluğundadır — bir sonraki satırı çağır, sonra dönüş adresini stack’ten çek. CPU gerçek çalışma adresini push etmiştir, yani kod işlemciye nerede olduğunu sormuştur. Buradan sonrası hep o cevaba göre offset kullanır.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['runtime base resolved'],
    signals: [],
  },
  {
    id: 'kernel-verify-cpu',
    phase: 'os',
    title: { en: 'verify_cpu — Can This Chip Even Run It?', tr: 'verify_cpu — Bu İşlemci Bunu Çalıştırabilir mi?' },
    signal: 'verify_cpu',
    source: 'arch/x86/kernel/verify_cpu.S:38',
    description: {
      en: 'Before unpacking a 64-bit kernel onto a processor, it is worth asking whether the processor is 64-bit. This routine interrogates the CPU about its own capabilities and checks for long mode, the 64-bit operating mode of x86. A failure here is not a crash but a printed message and a halt — a wrong-kernel-for-this-machine mistake is common enough that telling the user plainly beats faulting three steps later with nothing on screen.',
      tr: '64-bit bir kernel’i bir işlemciye açmadan önce, işlemcinin 64-bit olup olmadığını sormakta fayda vardır. Bu rutin CPU’ya kendi yeteneklerini sorar ve long mode’u, yani x86’nın 64-bit çalışma kipini arar. Buradaki başarısızlık bir çökme değil, basılan bir mesaj ve duraklamadır — bu makineye yanlış kernel verme hatası yeterince yaygındır ve kullanıcıya açıkça söylemek, üç adım sonra ekranda hiçbir şey yokken fault vermekten iyidir.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['CPUID: long mode  present', 'verify_cpu  ok'],
    signals: [{ route: ['cpuBsp', 'cpuCache'], color: LOGIC, particles: 6, spread: 0.5 }],
  },
  {
    id: 'kernel-mem-encrypt',
    phase: 'os',
    title: { en: 'Is the Memory Encrypted?', tr: 'Bellek Şifreli mi?' },
    signal: 'sev_enable / early_tdx_detect',
    description: {
      en: 'On some server processors the memory controller encrypts everything written to DRAM, so that a machine\'s owner cannot read what a tenant is running. If that is switched on, it changes the meaning of every physical address the next steps will use, so it has to be settled before a single page table is built. AMD calls it SEV and Intel calls it TDX; both are asked here, and on an ordinary desktop both answer no.',
      tr: 'Bazı sunucu işlemcilerinde bellek denetleyicisi DRAM’e yazılan her şeyi şifreler; böylece makinenin sahibi, üzerinde çalışan kiracının ne yaptığını okuyamaz. Bu açıksa, sonraki adımların kullanacağı her fiziksel adresin anlamı değişir — dolayısıyla tek bir page table kurulmadan önce karara bağlanmalıdır. AMD buna SEV, Intel TDX diyor; ikisi de burada sorulur ve sıradan bir masaüstünde ikisi de hayır der.',
    },
    duration: 4600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['SEV: not active', 'TDX: not detected'],
    signals: [{ route: ['cpuBsp', 'ram'], color: LOGIC, particles: 5, spread: 0.5 }],
  },
  {
    id: 'kernel-longmode',
    phase: 'os',
    title: { en: 'Switching On 64-bit Mode', tr: '64-bit Moda Geçiş' },
    signal: 'lret → long mode',
    description: {
      en: "A processor cannot enter 64-bit mode without address translation already running, and address translation needs tables in memory describing it. So this code builds a deliberately crude set: a page table that maps each address straight to itself. Nothing is hidden or moved — the map is the identity — but it exists, which is all the CPU requires. With it loaded, one instruction flips the machine into long mode.",
      tr: 'Bir işlemci, adres çevirisi zaten çalışmadan 64-bit moda geçemez; adres çevirisi de bunu tarif eden bellek içi tablolara ihtiyaç duyar. Bu yüzden bu kod bilerek kaba bir set kurar: her adresi doğrudan kendisine eşleyen bir page table. Hiçbir şey gizlenmez ya da taşınmaz — harita birebirdir — ama vardır, ki CPU’nun istediği de sadece budur. O yüklendikten sonra tek bir talimat makineyi long mode’a çevirir.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['identity mapping built  0-4 GiB', 'CR0.PG = 1', 'entering long mode'],
    signals: [
      { route: ['cpuBsp', 'ram'], color: FW, label: 'page tables', particles: 10, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-startup64-dec',
    phase: 'os',
    title: { en: 'startup_64 — Four Levels or Five', tr: 'startup_64 — Dört Seviye mi Beş mi' },
    signal: 'configure_5level_paging()',
    source: 'arch/x86/boot/compressed/head_64.S:278',
    description: {
      en: 'Now running as a 64-bit program, the unpacker settles one structural question. The tables that translate addresses are a tree, and that tree is either four or five levels deep — five reaches far more memory but costs an extra lookup on every miss. Since the depth is baked into every table built afterwards, it cannot be revisited later. It is decided here, once, and the rest of the boot inherits it.',
      tr: 'Artık 64-bit bir program olarak çalışan açıcı, yapısal bir soruyu karara bağlar. Adresleri çeviren tablolar bir ağaçtır ve bu ağaç ya dört ya beş seviyedir — beş çok daha fazla belleğe uzanır ama her ıskalamada fazladan bir arama maliyeti getirir. Derinlik sonradan kurulan her tabloya işlendiği için geri dönülemez. Burada, bir kez karar verilir ve boot’un geri kalanı onu devralır.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['paging: 4-level (57-bit VA not enabled)'],
    signals: [{ route: ['ram', 'cpuBsp'], color: FW, particles: 8, spread: 0.5 }],
  },

  // --- Unpacking -------------------------------------------------------------
  {
    id: 'kernel-extract',
    phase: 'os',
    title: { en: 'extract_kernel() — Checking GRUB\'s Homework', tr: 'extract_kernel() — GRUB’ın Ödevini Denetlemek' },
    signal: 'extract_kernel()',
    source: 'arch/x86/boot/compressed/misc.c:407',
    description: {
      en: "The first C function in the whole sequence, and its first act is distrust. The table GRUB filled in — the zero page, a fixed 4 KB layout holding the memory map, the command line and the video mode — is scrubbed: fields that older bootloaders left as garbage are zeroed. The kernel is about to make every decision based on this table, so anything not explicitly written by a bootloader it trusts is treated as noise.",
      tr: 'Tüm dizideki ilk C fonksiyonu ve ilk yaptığı şey güvensizlik. GRUB’ın doldurduğu tablo — zero page, memory map’i, komut satırını ve video modunu tutan sabit 4 KB’lık düzen — temizlenir: eski bootloader’ların çöp bıraktığı alanlar sıfırlanır. Kernel birazdan her kararını bu tabloya bakarak verecektir, dolayısıyla güvendiği bir bootloader tarafından açıkça yazılmamış her şey gürültü sayılır.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['early console in extract_kernel', 'boot_params sanitized'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: DATA, label: 'boot_params', particles: 10, spread: 0.55 },
    ],
  },
  {
    id: 'kernel-kaslr',
    phase: 'os',
    title: { en: 'choose_random_location() — Rolling the Dice', tr: 'choose_random_location() — Zar Atmak' },
    signal: 'choose_random_location()',
    source: 'arch/x86/boot/compressed/kaslr.c:862',
    description: {
      en: 'An attacker who knows exactly where a kernel function sits in memory has most of an exploit already. So the kernel refuses to be predictable: it picks a random address to unpack itself to, drawn from whatever entropy the machine can offer this early — the timestamp counter, the RDRAND instruction if present. This is KASLR, and it is why two boots of the same machine put the same function at different addresses.',
      tr: 'Bir kernel fonksiyonunun bellekte tam olarak nerede durduğunu bilen saldırgan, exploit’in çoğunu zaten elde etmiştir. Bu yüzden kernel öngörülebilir olmayı reddeder: kendini açacağı adresi rastgele seçer; bu kadar erken bir anda makinenin sunabildiği entropiden — timestamp counter’dan, varsa RDRAND talimatından — türetir. Buna KASLR denir ve aynı makinenin iki boot’unda aynı fonksiyonun farklı adreslere düşmesinin sebebi budur.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['KASLR using RDRAND', 'Physical randomization: 0x2f800000'],
    signals: [
      { route: ['cpuBsp', 'ram'], color: KERNEL, label: 'KASLR offset', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-decompress',
    phase: 'os',
    title: { en: 'decompress_kernel() — Unpacking', tr: 'decompress_kernel() — Paketten Çıkarma' },
    signal: 'decompress_kernel()',
    source: 'arch/x86/boot/compressed/misc.c:344',
    description: {
      en: "A kernel is roughly 40 MB of code shipped as a 12 MB file, because reading less from a slow disk is worth spending CPU cycles to expand. This is where the file pays that back. Which algorithm runs was fixed when the kernel was built — gzip, zstd, lzo and others are all supported — and the unpacker simply calls whichever one was compiled in, writing the result to the address the previous step picked.",
      tr: 'Bir kernel, 12 MB’lık bir dosya olarak dağıtılan kabaca 40 MB kodudur; çünkü yavaş bir diskten daha az okumak, genişletmek için CPU harcamaya değer. Dosya bu borcu burada öder. Hangi algoritmanın çalışacağı kernel derlenirken sabitlenmiştir — gzip, zstd, lzo ve diğerleri desteklenir — ve açıcı yalnızca derlemeye giren hangisiyse onu çağırıp sonucu bir önceki adımın seçtiği adrese yazar.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['Decompressing Linux... ', 'Parsing ELF... done.'],
    signals: [
      { route: ['ram', 'ram'], color: KERNEL, label: 'gunzip', particles: 16, spread: 0.85 },
    ],
  },
  {
    id: 'kernel-parse-elf',
    phase: 'os',
    title: { en: 'parse_elf() — Laying Out the Sections', tr: 'parse_elf() — Bölümleri Yerleştirmek' },
    signal: 'parse_elf()',
    source: 'arch/x86/boot/compressed/misc.c:281',
    description: {
      en: "What came out of the decompressor is an ELF file — the standard container that says which bytes are code, which are data, and where each belongs. This step reads that header and copies each section to its proper address. Then it fixes the addresses inside the code itself: because the random offset moved everything, every hard-coded pointer in the kernel is wrong by exactly that amount, and each one has to be adjusted before a single instruction runs.",
      tr: 'Açıcıdan çıkan şey bir ELF dosyasıdır — hangi baytların kod, hangilerinin veri olduğunu ve her birinin nereye ait olduğunu söyleyen standart kap. Bu adım o başlığı okur ve her bölümü kendi adresine kopyalar. Ardından kodun içindeki adresleri düzeltir: rastgele offset her şeyi kaydırdığı için kernel’deki her sabit pointer tam o kadar yanlıştır ve tek bir talimat çalışmadan önce hepsinin düzeltilmesi gerekir.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['relocations applied', 'Booting the kernel (entry_offset: 0x0).'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: KERNEL, label: 'jmp vmlinux', particles: 14, spread: 0.6 },
    ],
  },

  // --- The real kernel: first assembly ---------------------------------------
  {
    id: 'kernel-startup64',
    phase: 'os',
    title: { en: 'startup_64 — The Kernel\'s First Instruction', tr: 'startup_64 — Kernel’in İlk Talimatı' },
    signal: 'startup_64',
    source: 'arch/x86/kernel/head_64.S:38',
    description: {
      en: 'Everything up to now was scaffolding — a helper program that unpacked a file and then jumped out of the way. This is the kernel itself, the first instruction of the thing that will still be running when the machine shuts down years from now. It inherits a 64-bit processor, a crude identity map, and the same zero page GRUB wrote. It owns nothing else yet.',
      tr: 'Şimdiye kadarki her şey iskeleydi — bir dosyayı açıp sonra yoldan çekilen bir yardımcı program. Bu, kernel’in kendisidir; yıllar sonra makine kapanırken hâlâ çalışıyor olacak şeyin ilk talimatı. 64-bit bir işlemciyi, kaba bir identity map’i ve GRUB’ın yazdığı aynı zero page’i devralır. Henüz başka hiçbir şeyi yoktur.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram', 'cpuCache'],
    console: ['vmlinux entry: startup_64'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: KERNEL, label: 'startup_64', particles: 14, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-gdt-idt',
    phase: 'os',
    title: { en: 'Its Own Tables, Not the Bootloader\'s', tr: 'Kendi Tabloları, Bootloader’ınkiler Değil' },
    signal: 'setup_gdt_idt',
    description: {
      en: "Two tables tell an x86 processor how to behave: one describing memory regions and privilege, one listing what to run when something interrupts. Both currently belong to GRUB — sitting in memory the kernel is about to reuse for something else. So the kernel builds its own copies and points the CPU at them. It is not that GRUB's were wrong; it is that they are about to be overwritten.",
      tr: 'İki tablo bir x86 işlemcisine nasıl davranacağını söyler: biri bellek bölgelerini ve ayrıcalığı tarif eder, diğeri bir şey araya girdiğinde ne çalıştırılacağını listeler. İkisi de şu an GRUB’a aittir — kernel’in birazdan başka bir şey için kullanacağı bellekte durmaktadırlar. Bu yüzden kernel kendi kopyalarını kurar ve CPU’yu onlara yöneltir. Mesele GRUB’ınkilerin yanlış olması değil; birazdan üzerlerine yazılacak olmasıdır.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['GDT reloaded', 'early IDT installed'],
    signals: [{ route: ['cpuBsp', 'ram'], color: LOGIC, particles: 6, spread: 0.5 }],
  },
  {
    id: 'kernel-pagetables',
    phase: 'os',
    title: { en: 'Page Tables It Intends to Keep', tr: 'Kalıcı Olacak Page Table’lar' },
    signal: '__startup_64()',
    description: {
      en: 'The identity map from the decompressor was a means to an end — enough to turn on 64-bit mode, nothing more. Here the kernel lays the first tables it actually intends to live in, including the mapping that puts kernel code in the upper half of every address space. That upper-half placement is why the kernel stays reachable from inside every process later, without a single table switch.',
      tr: 'Açıcıdaki identity map bir araçtı — 64-bit modu açmaya yetecek kadar, fazlası değil. Burada kernel gerçekten içinde yaşamayı düşündüğü ilk tabloları serer; buna kernel kodunu her adres uzayının üst yarısına yerleştiren eşleme de dahildir. Kernel’in ilerideki her sürecin içinden tek bir tablo değişimi olmadan erişilebilir kalmasının sebebi bu üst yarı yerleşimidir.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['kernel mapped at 0xffffffff81000000'],
    signals: [
      { route: ['cpuBsp', 'ram'], color: FW, label: 'swapper_pg_dir', particles: 9, spread: 0.55 },
    ],
  },
  {
    id: 'kernel-common-startup',
    phase: 'os',
    title: { en: 'common_startup_64 — Shared Ground', tr: 'common_startup_64 — Ortak Zemin' },
    signal: 'common_startup_64',
    source: 'arch/x86/kernel/head_64.S:198',
    description: {
      en: 'This label exists because two very different arrivals need identical treatment. The boot processor reaches it now; every other core on the chip will reach it much later, when it is woken during SMP bringup. Both need the same control registers set, the same page tables loaded, the same stack discipline — so the code is written once and both paths converge here.',
      tr: 'Bu etiket, çok farklı iki gelişin birebir aynı muameleye ihtiyaç duyması yüzünden vardır. Boot işlemcisi buraya şimdi ulaşır; yongadaki diğer her çekirdek çok daha sonra, SMP bringup sırasında uyandırıldığında ulaşacaktır. İkisinin de aynı kontrol register’larının kurulmasına, aynı page table’ların yüklenmesine, aynı stack disiplinine ihtiyacı vardır — bu yüzden kod bir kez yazılır ve iki yol burada birleşir.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: ['CR4 = 0x000406f0', 'cr3 = swapper_pg_dir'],
    signals: [{ route: ['cpuBsp', 'cpuCache'], color: LOGIC, particles: 7, spread: 0.5 }],
  },
  {
    id: 'kernel-to-c',
    phase: 'os',
    title: { en: 'Handing Over to C', tr: 'C’ye Devretmek' },
    signal: 'early_setup_idt',
    description: {
      en: 'Assembly has taken this as far as it usefully can. One more piece is needed before C code is safe to run: a table of handlers for the faults that will inevitably happen while memory is still half-configured. With that installed, a fault prints something instead of triple-faulting the machine into a silent reboot — and the kernel calls its first proper C function.',
      tr: 'Assembly bunu faydalı olabileceği yere kadar getirdi. C kodunun güvenle çalışması için bir parça daha gerekir: bellek hâlâ yarı yapılandırılmışken kaçınılmaz olarak oluşacak fault’lar için bir handler tablosu. O kurulduktan sonra bir fault, makineyi sessiz bir yeniden başlatmaya sürükleyen triple fault yerine bir şeyler basar — ve kernel ilk düzgün C fonksiyonunu çağırır.',
    },
    duration: 4600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['early exception handlers ready'],
    signals: [],
  },

  // --- First C ---------------------------------------------------------------
  {
    id: 'kernel-x86-64-start',
    phase: 'os',
    title: { en: 'x86_64_start_kernel() — Into C', tr: 'x86_64_start_kernel() — C Dünyasına' },
    signal: 'x86_64_start_kernel()',
    source: 'arch/x86/kernel/head64.c:222',
    description: {
      en: 'From here the kernel is readable by anyone who knows C, which is most of why the boot is documented at all. This function is still deeply architecture-specific — it exists only on x86-64 — and its job is to finish the last few things that cannot be expressed portably, then call the function that every architecture shares.',
      tr: 'Buradan itibaren kernel, C bilen herkes tarafından okunabilir; boot’un genel olarak belgelenebilir olmasının sebebi büyük ölçüde budur. Bu fonksiyon hâlâ derinlemesine mimariye özgüdür — yalnızca x86-64’te vardır — ve işi, taşınabilir biçimde ifade edilemeyen son birkaç şeyi bitirip ardından her mimarinin ortak kullandığı fonksiyonu çağırmaktır.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: ['x86_64_start_kernel()'],
    signals: [{ route: ['cpuBsp', 'ram'], color: KERNEL, particles: 8, spread: 0.5 }],
  },
  {
    id: 'kernel-clear-bss',
    phase: 'os',
    title: { en: 'clear_bss() — Zeroing What Was Never Written', tr: 'clear_bss() — Hiç Yazılmamış Olanı Sıfırlamak' },
    signal: 'clear_bss()',
    source: 'arch/x86/kernel/head64.c:177',
    description: {
      en: 'A variable declared without a starting value is not stored in the kernel file at all — writing megabytes of zeros to disk would be absurd. Instead the file records only how much space to reserve, in a region called .bss, and someone has to actually zero it at runtime. That someone is here. Until this line runs, every uninitialised variable in the kernel holds whatever the previous occupant of that memory left behind.',
      tr: 'Başlangıç değeri olmadan tanımlanan bir değişken kernel dosyasında hiç saklanmaz — diske megabaytlarca sıfır yazmak saçma olurdu. Bunun yerine dosya yalnızca ne kadar yer ayrılacağını .bss denen bir bölgede kaydeder ve birinin bunu çalışma anında gerçekten sıfırlaması gerekir. O biri burasıdır. Bu satır çalışana kadar kernel’deki her ilklenmemiş değişken, o belleğin önceki sakininden kalan ne varsa onu tutar.',
    },
    duration: 4600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['.bss cleared'],
    signals: [{ route: ['cpuBsp', 'ram'], color: LOGIC, particles: 8, spread: 0.6 }],
  },
  {
    id: 'kernel-copy-bootdata',
    phase: 'os',
    title: { en: 'copy_bootdata() — GRUB\'s Data Comes Inside', tr: 'copy_bootdata() — GRUB’ın Verisi İçeri Giriyor' },
    signal: 'copy_bootdata()',
    source: 'arch/x86/kernel/head64.c:194',
    description: {
      en: "The zero page has been sitting in memory GRUB allocated, and the kernel is about to start handing that memory out. So the whole structure is copied into a variable of the kernel's own — boot_params — along with the command line. This is the exact moment the bootloader's contribution stops being borrowed and becomes the kernel's. Everything GRUB learned about this machine now lives inside the kernel.",
      tr: 'Zero page şimdiye kadar GRUB’ın ayırdığı bellekte duruyordu ve kernel birazdan o belleği dağıtmaya başlayacak. Bu yüzden tüm yapı, komut satırıyla birlikte, kernel’in kendi değişkenine — boot_params — kopyalanır. Bootloader’ın katkısının ödünç olmaktan çıkıp kernel’in malı olduğu an tam olarak burasıdır. GRUB’ın bu makine hakkında öğrendiği her şey artık kernel’in içinde yaşıyor.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['boot_params copied', 'Command line: BOOT_IMAGE=/vmlinuz root=/dev/nvme0n1p2 ro quiet'],
    signals: [
      { route: ['ram', 'cpuBsp'], color: DATA, label: 'boot_params', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-reservations',
    phase: 'os',
    title: { en: 'x86_64_start_reservations() — Last Stop', tr: 'x86_64_start_reservations() — Son Durak' },
    signal: 'x86_64_start_reservations()',
    source: 'arch/x86/kernel/head64.c:294',
    description: {
      en: 'A short function whose only real purpose is to be the last x86-specific thing that happens before the portable kernel begins. It applies quirks for platforms known to misbehave, then makes the call that a kernel on ARM, RISC-V or PowerPC would also make from its own equivalent of this place.',
      tr: 'Tek gerçek amacı, taşınabilir kernel başlamadan önce gerçekleşen son x86’ya özgü şey olmak olan kısa bir fonksiyon. Yanlış davrandığı bilinen platformlar için quirk’leri uygular, sonra ARM, RISC-V ya da PowerPC üzerindeki bir kernel’in de kendi muadili yerden yapacağı çağrıyı yapar.',
    },
    duration: 4400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['x86_64_start_reservations()'],
    signals: [],
  },

  // --- setup_arch ------------------------------------------------------------
  {
    id: 'kernel-setup-arch',
    phase: 'os',
    title: { en: 'setup_arch() — Everything Machine-Specific', tr: 'setup_arch() — Makineye Özgü Her Şey' },
    signal: 'setup_arch()',
    source: 'arch/x86/kernel/setup.c:884',
    description: {
      en: "start_kernel() has barely begun and it already calls out to this — over a thousand lines of code that exists in a different form for every architecture Linux supports. Its job is to turn 'a computer' into 'this computer': find the memory, find the CPUs, find the interrupt controllers. Nothing after it can be portable until it finishes.",
      tr: 'start_kernel() daha yeni başlamışken hemen buraya çıkar — Linux’un desteklediği her mimari için farklı bir biçimde var olan, bin satırı aşkın bir kod. İşi, ‘bir bilgisayarı’ ‘bu bilgisayara’ çevirmektir: belleği bul, CPU’ları bul, kesme denetleyicilerini bul. O bitmeden sonrasındaki hiçbir şey taşınabilir olamaz.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram', 'chipset'],
    console: ['setup_arch()'],
    signals: [{ route: ['cpuBsp', 'chipset'], color: LOGIC, particles: 8, spread: 0.5 }],
  },
  {
    id: 'kernel-early-cpu',
    phase: 'os',
    title: { en: 'Asking the CPU What It Is', tr: 'CPU’ya Ne Olduğunu Sormak' },
    signal: 'early_cpu_init()',
    description: {
      en: 'The kernel now reads the processor\'s own identification — vendor, family, model, and the long list of features it claims to support. This matters far beyond a banner line: dozens of later decisions branch on it, and so do the mitigations for hardware bugs like Spectre and Meltdown, which are simply code paths enabled for the exact models known to be affected.',
      tr: 'Kernel artık işlemcinin kendi kimliğini okur — üretici, aile, model ve desteklediğini iddia ettiği uzun özellik listesi. Bunun önemi bir başlık satırının çok ötesindedir: sonraki onlarca karar buna göre dallanır, Spectre ve Meltdown gibi donanım hatalarına karşı önlemler de öyle — ki bunlar yalnızca etkilendiği bilinen modeller için açılan kod yollarıdır.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['CPU: 13th Gen Intel(R) Core(TM) i7-13700K', 'Spectre V2 : Mitigation: Enhanced IBRS'],
    signals: [{ route: ['cpuBsp', 'cpuCache'], color: LOGIC, particles: 6, spread: 0.5 }],
  },
  {
    id: 'kernel-e820',
    phase: 'os',
    title: { en: 'e820__memory_setup() — Reading GRUB\'s Map', tr: 'e820__memory_setup() — GRUB’ın Haritasını Okumak' },
    signal: 'e820__memory_setup()',
    source: 'arch/x86/kernel/e820.c:1272',
    description: {
      en: "Here the chain closes a loop. The kernel has no way to ask the firmware what memory exists — that conversation required real mode, which was skipped entirely. It reads the answer GRUB wrote into the zero page instead: E820, a list of address ranges each tagged usable, reserved, or broken. Every allocation the kernel ever makes is bounded by this list, and the list is secondhand.",
      tr: 'Burada zincir bir halkayı kapatır. Kernel’in firmware’e hangi belleğin var olduğunu sorma imkânı yoktur — o konuşma real mode gerektiriyordu ve real mode tamamen atlandı. Onun yerine GRUB’ın zero page’e yazdığı cevabı okur: E820, her biri kullanılabilir, ayrılmış ya da bozuk olarak etiketlenmiş adres aralıklarının listesi. Kernel’in yapacağı her ayırma bu listeyle sınırlıdır ve liste ikinci eldendir.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'BIOS-provided physical RAM map:',
      'BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable',
      'BIOS-e820: [mem 0x0000000000100000-0x00000000bffdffff] usable',
    ],
    signals: [
      { route: ['ram', 'cpuBsp'], color: DATA, label: 'E820', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-cmdline',
    phase: 'os',
    title: { en: 'Reading the Command Line', tr: 'Komut Satırını Okumak' },
    signal: 'parse_early_param()',
    description: {
      en: 'The string GRUB passed down is parsed — but only partially, and on purpose. A handful of options change decisions that are about to be made in the next few lines, before the machinery for handling the rest even exists. Those are picked out now; everything else waits for a second pass later. It is a rare case where the kernel reads the same input twice because the first read has to happen too early.',
      tr: 'GRUB’ın aktardığı dizi ayrıştırılır — ama yalnızca kısmen ve bilerek. Bir avuç seçenek, birkaç satır sonra verilecek kararları etkiler; üstelik geri kalanını işleyecek mekanizma henüz yoktur. Onlar şimdi ayıklanır, diğer her şey sonraki bir tur için bekler. Kernel’in aynı girdiyi iki kez okuduğu ender bir durum — çünkü ilk okumanın çok erken olması gerekir.',
    },
    duration: 4600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['Kernel command line: BOOT_IMAGE=/vmlinuz root=/dev/nvme0n1p2 ro quiet'],
    signals: [],
  },
  {
    id: 'kernel-memblock',
    phase: 'os',
    title: { en: 'The Allocator Before the Allocator', tr: 'Ayırıcıdan Önceki Ayırıcı' },
    signal: 'e820__memblock_setup()',
    description: {
      en: "The kernel needs to allocate memory in order to build the system that allocates memory — a genuine chicken-and-egg problem. The answer is memblock, a deliberately primitive allocator: a plain list of reserved and free ranges, no freeing worth the name, no performance to speak of. It is thrown away once the real allocator is up, and it exists only to bootstrap it.",
      tr: 'Kernel’in, bellek ayıran sistemi kurabilmek için bellek ayırması gerekir — gerçek bir yumurta-tavuk sorunu. Cevap memblock’tur; bilerek ilkel bırakılmış bir ayırıcı: ayrılmış ve boş aralıkların düz bir listesi, adı anılmaya değer bir serbest bırakma yok, performans hiç yok. Gerçek ayırıcı ayağa kalktığında atılır ve zaten yalnızca onu başlatmak için vardır.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['memblock: reserved[0x0] [0x1000000-0x2fffffff]'],
    signals: [{ route: ['cpuBsp', 'ram'], color: FW, particles: 8, spread: 0.55 }],
  },
  {
    id: 'kernel-mem-mapping',
    phase: 'os',
    title: { en: 'init_mem_mapping() — Mapping All of It', tr: 'init_mem_mapping() — Hepsini Haritalamak' },
    signal: 'init_mem_mapping()',
    source: 'arch/x86/mm/init.c:758',
    description: {
      en: 'Up to now only a few megabytes have been reachable — enough for the kernel to run, nothing more. This builds the page tables covering all installed RAM, so that the sixty-fourth gigabyte is as addressable as the first. It uses memblock to allocate the tables it needs, which is precisely the bootstrapping the previous step existed for.',
      tr: 'Şimdiye kadar yalnızca birkaç megabayt erişilebilirdi — kernel’in çalışmasına yetecek kadar, fazlası değil. Bu adım kurulu tüm RAM’i kapsayan page table’ları kurar; böylece altmış dördüncü gigabayt, birincisi kadar adreslenebilir olur. İhtiyaç duyduğu tabloları ayırmak için memblock’u kullanır — bir önceki adımın var oluş sebebi tam olarak bu başlatmadır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: ['init_mem_mapping: [mem 0x00000000-0xbffdffff]', 'Base memory trampoline at [0x99000]'],
    signals: [
      { route: ['cpuBsp', 'ram'], color: FW, label: 'page tables', particles: 12, spread: 0.65 },
    ],
  },
  {
    id: 'kernel-acpi',
    phase: 'os',
    title: { en: 'acpi_boot_init() — The Firmware\'s Inventory', tr: 'acpi_boot_init() — Firmware’in Envanteri' },
    signal: 'acpi_boot_init()',
    source: 'arch/x86/kernel/acpi/boot.c:1643',
    description: {
      en: 'Only the firmware knows how this particular board is wired — how many CPU cores exist, where the interrupt controllers sit, which power states the hardware supports. It left that knowledge in a set of tables in memory, the ACPI tables, and this is where the kernel reads them. The count of cores found here is what the SMP bringup will later act on.',
      tr: 'Bu kartın nasıl kablolandığını yalnızca firmware bilir — kaç CPU çekirdeği olduğunu, kesme denetleyicilerinin nerede durduğunu, donanımın hangi güç durumlarını desteklediğini. Bu bilgiyi bellekte bir tablo kümesinde bıraktı: ACPI tabloları. Kernel onları burada okur. Burada bulunan çekirdek sayısı, ilerideki SMP bringup’ın üzerine hareket edeceği sayıdır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['chipset', 'cpuBsp', 'cpuAp'],
    console: [
      'ACPI: RSDP 0x00000000000F0490 000024',
      'ACPI: MADT: 16 CPUs detected',
      'ACPI: IOAPIC (id[0x02] address[0xfec00000])',
    ],
    signals: [
      { route: ['chipset', 'cpuBsp'], color: DATA, label: 'ACPI tables', particles: 10, spread: 0.6 },
    ],
  },

  // --- start_kernel ----------------------------------------------------------
  {
    id: 'kernel-start-kernel',
    phase: 'os',
    title: { en: 'start_kernel() — The Portable Kernel Begins', tr: 'start_kernel() — Taşınabilir Kernel Başlıyor' },
    signal: 'start_kernel()',
    source: 'init/main.c:972',
    description: {
      en: 'The same function runs here on every machine Linux supports, from a phone to a mainframe. Its very first act is to switch interrupts off, and they stay off for the next couple of hundred lines: the subsystems that would handle an interrupt do not exist yet, so an interrupt arriving now would have nowhere to go.',
      tr: 'Bu fonksiyon, telefondan anabilgisayara kadar Linux’un desteklediği her makinede aynı şekilde çalışır. İlk yaptığı şey kesmeleri kapatmaktır ve sonraki birkaç yüz satır boyunca kapalı kalırlar: bir kesmeyi karşılayacak alt sistemler henüz yoktur, dolayısıyla şimdi gelen bir kesmenin gidecek yeri olmazdı.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['start_kernel()', 'local_irq_disable()'],
    signals: [{ route: ['cpuBsp', 'ram'], color: KERNEL, particles: 8, spread: 0.5 }],
  },
  {
    id: 'kernel-banner',
    phase: 'os',
    title: { en: 'The First dmesg Line', tr: 'İlk dmesg Satırı' },
    signal: 'linux_banner',
    description: {
      en: 'The kernel prints its version, the compiler that built it, and the build date. Nobody sees it yet — the console driver will not exist for another two hundred lines — so it goes into a memory buffer and waits. This is why dmesg can show you messages from before the screen was working: they were all recorded and replayed once there was somewhere to send them.',
      tr: 'Kernel sürümünü, kendisini derleyen derleyiciyi ve derleme tarihini basar. Bunu henüz kimse görmez — konsol sürücüsü iki yüz satır daha var olmayacaktır — bu yüzden mesaj bir bellek tamponuna gider ve bekler. dmesg’in ekran çalışmadan önceki mesajları gösterebilmesinin sebebi budur: hepsi kaydedilmiş ve gönderilecek bir yer bulununca tekrar oynatılmıştır.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['[    0.000000] Linux version 7.2.0-rc6 (gcc-14) #1 SMP PREEMPT_DYNAMIC'],
    signals: [{ route: ['cpuBsp', 'ram'], color: LOGIC, particles: 6, spread: 0.5 }],
  },
  {
    id: 'kernel-percpu',
    phase: 'os',
    title: { en: 'setup_per_cpu_areas() — A Copy Each', tr: 'setup_per_cpu_areas() — Her Birine Bir Kopya' },
    signal: 'setup_per_cpu_areas()',
    source: 'arch/x86/kernel/setup_percpu.c:111',
    description: {
      en: 'When sixteen cores update one shared counter, they spend most of their time fighting over the cache line holding it. The kernel sidesteps this by giving each core its own private copy of such variables — per-CPU variables — so a core touches only memory no other core wants. This is one of the largest single reasons Linux scales across many cores, and it has to be set up before anything starts counting.',
      tr: 'On altı çekirdek tek bir paylaşılan sayacı güncellediğinde, zamanlarının çoğunu o sayacı tutan cache line’ı için kavga ederek geçirirler. Kernel bunu, böyle değişkenlerin her çekirdeğe özel bir kopyasını vererek aşar — per-CPU variables — böylece bir çekirdek yalnızca başka hiçbir çekirdeğin istemediği belleğe dokunur. Linux’un çok çekirdekte ölçeklenmesinin en büyük tek sebeplerinden biridir ve herhangi bir şey saymaya başlamadan önce kurulmalıdır.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp', 'ram'],
    console: ['percpu: Embedded 64 pages/cpu s225280 r8192 d28672'],
    signals: [
      { route: ['ram', 'cpuAp'], color: KERNEL, label: 'per-CPU', particles: 10, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-mm-core',
    phase: 'os',
    title: { en: 'mm_core_init() — Memory On Demand', tr: 'mm_core_init() — İstek Üzerine Bellek' },
    signal: 'mm_core_init()',
    source: 'mm/mm_init.c:2706',
    description: {
      en: "Until now the kernel could not request memory — it could only mark regions as taken, using the primitive list from earlier. Here a real allocator takes over: the buddy allocator, which manages free memory by repeatedly halving blocks until one is the right size, and merging neighbours back together when they are freed. From this line onward kmalloc works, and the rest of the kernel can finally allocate like ordinary software.",
      tr: 'Şimdiye kadar kernel bellek isteyemiyordu — yalnızca daha önceki ilkel listeyi kullanarak bölgeleri alınmış diye işaretleyebiliyordu. Burada gerçek bir ayırıcı devreye girer: buddy allocator, boş belleği doğru boyuta ulaşana dek blokları tekrar tekrar ikiye bölerek yöneten ve serbest bırakıldıklarında komşuları yeniden birleştiren yapı. Bu satırdan itibaren kmalloc çalışır ve kernel’in geri kalanı nihayet sıradan bir yazılım gibi bellek ayırabilir.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpuBsp'],
    console: [
      'Memory: 15873284K/16777216K available',
      'SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=16',
    ],
    signals: [
      { route: ['ram', 'cpuBsp'], color: KERNEL, label: 'kmalloc', particles: 14, spread: 0.7 },
    ],
  },
  {
    id: 'kernel-trap-init',
    phase: 'os',
    title: { en: 'trap_init() — When Things Go Wrong', tr: 'trap_init() — İşler Ters Gittiğinde' },
    signal: 'trap_init()',
    source: 'arch/x86/kernel/traps.c:1661',
    description: {
      en: 'A processor reacts to problems — a division by zero, a bad memory access, an illegal instruction — by looking up an entry in a table and jumping there. The early version of that table only had to survive boot. This installs the real one, with handlers that can report a fault properly, print a stack trace, and kill the offending process instead of the machine.',
      tr: 'Bir işlemci sorunlara — sıfıra bölme, hatalı bellek erişimi, geçersiz talimat — bir tablodaki girdiye bakıp oraya atlayarak tepki verir. O tablonun erken sürümünün yalnızca boot’u atlatması gerekiyordu. Bu adım gerçek olanı kurar: bir fault’u düzgün raporlayabilen, stack trace basabilen ve makine yerine hatalı süreci sonlandırabilen handler’larla.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['trap_init(): IDT populated'],
    signals: [{ route: ['cpuBsp', 'ram'], color: LOGIC, particles: 7, spread: 0.5 }],
  },
  {
    id: 'kernel-sched-init',
    phase: 'os',
    title: { en: 'sched_init() — Something to Run Things', tr: 'sched_init() — Bir Şeyleri Çalıştıracak Şey' },
    signal: 'sched_init()',
    source: 'kernel/sched/core.c:8915',
    description: {
      en: "Everything so far has been a single thread of execution with nothing to switch to. This builds the scheduler — the part that decides which task runs on which core and for how long — along with the run queues it manages. It also formally registers the code currently executing as a task, so that the boot itself becomes something the scheduler knows about rather than something outside its world.",
      tr: 'Şimdiye kadarki her şey, geçilecek başka bir şeyi olmayan tek bir yürütme akışıydı. Bu adım scheduler’ı kurar — hangi görevin hangi çekirdekte ve ne kadar süre çalışacağına karar veren parça — ve yönettiği çalışma kuyruklarını. Ayrıca hâlihazırda çalışan kodu resmen bir task olarak kaydeder; böylece boot’un kendisi, scheduler’ın dünyasının dışındaki bir şey değil, bildiği bir şey hâline gelir.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: ['sched_init(): 16 run queues', 'rcu: Preemptible hierarchical RCU implementation.'],
    signals: [
      { route: ['cpuBsp', 'cpuAp'], color: KERNEL, label: 'run queues', particles: 10, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-rcu-init',
    phase: 'os',
    title: { en: 'rcu_init() — Reading Without Locking', tr: 'rcu_init() — Kilitlemeden Okumak' },
    signal: 'rcu_init()',
    source: 'kernel/rcu/tree.c:4903',
    description: {
      en: 'Data read constantly and written rarely — routing tables, lists of open files — would be crippled if every reader had to take a lock. RCU solves this by letting readers proceed with no lock at all: a writer builds a new version, swaps a pointer to it, and waits until every core has passed through a point where it certainly holds no old reference before freeing the old copy. Much of the kernel depends on it, so it must exist before those parts start.',
      tr: 'Sürekli okunan ve nadiren yazılan veriler — yönlendirme tabloları, açık dosya listeleri — her okuyucunun kilit alması gerekseydi felç olurdu. RCU bunu, okuyucuların hiç kilit almadan ilerlemesine izin vererek çözer: yazan yeni bir sürüm kurar, ona bir pointer takas eder ve eski kopyayı serbest bırakmadan önce her çekirdeğin, kesinlikle eski bir referans tutmadığı bir noktadan geçmesini bekler. Kernel’in çoğu buna bağlıdır, dolayısıyla o parçalar başlamadan önce var olmalıdır.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: ['rcu: RCU restricting CPUs from NR_CPUS=8192 to nr_cpu_ids=16'],
    signals: [{ route: ['cpuAp', 'cpuBsp'], color: KERNEL, particles: 9, spread: 0.55 }],
  },
  {
    id: 'kernel-tick',
    phase: 'os',
    title: { en: 'tick_init() — A Heartbeat', tr: 'tick_init() — Bir Kalp Atışı' },
    signal: 'tick_init()',
    source: 'kernel/time/tick-common.c:591',
    description: {
      en: "A scheduler that cannot interrupt a running task cannot take the CPU back from it. The fix is a hardware timer firing at a fixed rate — the tick — which gives the kernel a regular chance to reconsider what should be running. Everything with a deadline hangs off this: timeouts, delays, the accounting that decides a task has had its share.",
      tr: 'Çalışan bir görevi kesemeyen bir scheduler, CPU’yu ondan geri alamaz. Çözüm, sabit bir hızda tetiklenen bir donanım zamanlayıcısıdır — tick — ve bu, kernel’e neyin çalışması gerektiğini yeniden düşünmek için düzenli bir fırsat verir. Süresi olan her şey buna asılıdır: timeout’lar, gecikmeler, bir görevin payını doldurduğuna karar veren muhasebe.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'chipset'],
    console: ['clocksource: refined-jiffies: mask: 0xffffffff', 'NR_IRQS: 4352'],
    signals: [
      { route: ['chipset', 'cpuBsp'], color: LOGIC, label: 'tick', particles: 8, spread: 0.5 },
    ],
  },
  {
    id: 'kernel-timekeeping',
    phase: 'os',
    title: { en: 'timekeeping_init() — What Time Is It?', tr: 'timekeeping_init() — Saat Kaç?' },
    signal: 'timekeeping_init()',
    source: 'kernel/time/timekeeping.c:2037',
    description: {
      en: "Counting ticks tells the kernel how long it has been running; it says nothing about what day it is. This picks a hardware counter to measure elapsed time accurately — on a modern x86 chip, the one that increments with every processor cycle — and establishes the relationship between that counter and wall-clock time. Two different notions of time, and the kernel needs both.",
      tr: 'Tick saymak kernel’e ne kadar süredir çalıştığını söyler; hangi gün olduğu hakkında hiçbir şey söylemez. Bu adım, geçen süreyi doğru ölçmek için bir donanım sayacı seçer — modern bir x86 yongasında her işlemci çevriminde artan sayaç — ve o sayaçla duvar saati arasındaki ilişkiyi kurar. İki farklı zaman kavramı ve kernel’in ikisine de ihtiyacı var.',
    },
    duration: 5000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['tsc: Detected 3400.000 MHz processor', 'clocksource: tsc-early selected'],
    signals: [{ route: ['cpuBsp', 'chipset'], color: LOGIC, particles: 7, spread: 0.5 }],
  },
  {
    id: 'kernel-irq-enable',
    phase: 'os',
    title: { en: 'Interrupts Come Back On', tr: 'Kesmeler Geri Açılıyor' },
    signal: 'local_irq_enable()',
    description: {
      en: 'Two hundred lines ago the kernel switched interrupts off because nothing could have handled one. Now the tables are populated, the handlers are installed, the timer has somewhere to report to — and this single line lets the hardware speak again. From here the kernel is reactive rather than purely sequential: a device can demand attention at any moment.',
      tr: 'İki yüz satır önce kernel kesmeleri kapatmıştı, çünkü gelen bir kesmeyi karşılayabilecek hiçbir şey yoktu. Artık tablolar dolu, handler’lar kurulu, zamanlayıcının raporlayacağı bir yer var — ve bu tek satır donanımın yeniden konuşmasına izin veriyor. Buradan itibaren kernel salt sıralı değil, tepkiseldir: bir aygıt her an ilgi talep edebilir.',
    },
    duration: 4600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'chipset'],
    console: ['local_irq_enable()'],
    signals: [
      { route: ['chipset', 'cpuBsp'], color: DATA, label: 'IRQ', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-console',
    phase: 'os',
    title: { en: 'console_init() — Someone Is Watching', tr: 'console_init() — Artık Biri İzliyor' },
    signal: 'console_init()',
    source: 'kernel/printk/printk.c:4384',
    description: {
      en: 'Every message the kernel has printed since the version banner has been accumulating in a buffer with no way out. This registers the console drivers — the framebuffer GRUB set up, a serial port if one is configured — and the entire backlog is flushed at once. On a real machine this is the moment text appears, which is why the first thing you see is never the first thing that happened.',
      tr: 'Kernel’in sürüm başlığından beri bastığı her mesaj, çıkışı olmayan bir tamponda birikiyordu. Bu adım konsol sürücülerini kaydeder — GRUB’ın kurduğu framebuffer, yapılandırılmışsa bir seri port — ve tüm birikmiş kayıt bir anda boşaltılır. Gerçek bir makinede metnin belirdiği an budur; gördüğün ilk şeyin hiçbir zaman olan ilk şey olmamasının sebebi de budur.',
    },
    duration: 5600,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['pcie', 'cpuBsp'],
    console: [
      'printk: console [tty0] enabled',
      '[    0.000000] Linux version 7.2.0-rc6 (gcc-14) #1 SMP',
      '[    0.041] Memory: 15873284K/16777216K available',
    ],
    signals: [
      { route: ['cpuBsp', 'pcie'], color: DATA, label: 'console', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-calibrate',
    phase: 'os',
    title: { en: 'calibrate_delay() — How Fast Is This?', tr: 'calibrate_delay() — Bu Ne Kadar Hızlı?' },
    signal: 'calibrate_delay()',
    source: 'init/calibrate.c:278',
    description: {
      en: 'Some drivers must wait a precise number of microseconds for hardware to settle, and the simplest way is a counting loop. But a loop takes different real time on different processors, so the kernel measures how many iterations fit into a known interval. The resulting number is printed as BogoMIPS — a name chosen to warn people it is not a performance measurement, which has not stopped anyone from comparing it.',
      tr: 'Bazı sürücüler donanımın oturması için tam olarak belirli bir mikrosaniye beklemek zorundadır ve en basit yol bir sayma döngüsüdür. Ama bir döngü farklı işlemcilerde farklı gerçek süre alır; bu yüzden kernel, bilinen bir aralığa kaç yineleme sığdığını ölçer. Çıkan sayı BogoMIPS olarak basılır — insanları bunun bir performans ölçümü olmadığı konusunda uyarmak için seçilmiş bir isim, ki bu kimseyi karşılaştırma yapmaktan alıkoymamıştır.',
    },
    duration: 4800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['[    0.112] Calibrating delay loop (skipped), value calculated using timer frequency.. 6800.00 BogoMIPS (lpj=3400000)'],
    signals: [{ route: ['cpuBsp', 'cpuCache'], color: LOGIC, particles: 6, spread: 0.5 }],
  },
  {
    id: 'kernel-vfs',
    phase: 'os',
    title: { en: 'vfs_caches_init() — The Idea of a File', tr: 'vfs_caches_init() — Dosya Fikri' },
    signal: 'vfs_caches_init()',
    source: 'fs/dcache.c:3510',
    description: {
      en: "No disk has been touched yet, and no filesystem driver has loaded. What is built here is the layer above all of them: the VFS, which defines what a file and a directory are, so that ext4, NVMe-backed XFS and a network share can all be opened with the same call. It also creates the in-memory root, /, which currently contains nothing at all — but it exists, and something can now be mounted onto it.",
      tr: 'Henüz hiçbir diske dokunulmadı ve hiçbir dosya sistemi sürücüsü yüklenmedi. Burada kurulan şey hepsinin üstündeki katmandır: VFS, yani bir dosyanın ve bir dizinin ne olduğunu tanımlayan katman — böylece ext4, NVMe üzerindeki XFS ve bir ağ paylaşımı aynı çağrıyla açılabilir. Ayrıca bellekteki kökü, /, oluşturur; şu an içinde hiçbir şey yoktur — ama vardır ve artık üzerine bir şey mount edilebilir.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'm2'],
    console: [
      'VFS: Disk quotas dquot_6.6.0',
      'VFS: Dentry cache hash table entries: 1048576',
      'Mount-cache hash table entries: 32768',
    ],
    signals: [
      { route: ['ram', 'm2'], color: DATA, label: 'VFS', particles: 10, spread: 0.6 },
    ],
  },

  // --- The first tasks -------------------------------------------------------
  {
    id: 'kernel-rest-init',
    phase: 'os',
    title: { en: 'rest_init() — The Point of No Return', tr: 'rest_init() — Dönüşü Olmayan Nokta' },
    signal: 'rest_init()',
    source: 'init/main.c:671',
    description: {
      en: 'The last line of start_kernel(), and it never comes back — the function is marked as one that cannot return. Everything the kernel needed to do by itself, alone and in order, is done. What remains cannot be done sequentially, so this function stops being a program and starts being three of them.',
      tr: 'start_kernel()’in son satırı ve geri dönmez — fonksiyon, dönemeyecek olarak işaretlenmiştir. Kernel’in tek başına, sırayla yapması gereken her şey bitti. Geriye kalan sırayla yapılamaz; bu yüzden bu fonksiyon bir program olmayı bırakıp üç program olmaya başlar.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: ['rest_init()'],
    signals: [{ route: ['cpuBsp', 'cpuAp'], color: KERNEL, particles: 10, spread: 0.6 }],
  },
  {
    id: 'kernel-pid1',
    phase: 'os',
    title: { en: 'PID 1 Is Born — And the Order Matters', tr: 'PID 1 Doğuyor — ve Sıra Önemli' },
    signal: 'user_mode_thread(kernel_init)',
    description: {
      en: "The first task is created, and it takes process ID 1 — the number every Unix reserves for the ancestor of all other processes. The comment in the source explains why it must be created first: it needs that number, but it will soon want to spawn kernel threads, and the machinery for that does not exist yet. Create it second and it either gets the wrong number or crashes the kernel. One of the clearest cases in the boot where the order is the whole design.",
      tr: 'İlk task yaratılır ve process ID 1’i alır — her Unix’in diğer tüm süreçlerin atası için ayırdığı numara. Kaynaktaki yorum neden önce yaratılması gerektiğini açıklar: o numaraya ihtiyacı vardır, ama birazdan kernel thread’leri doğurmak isteyecektir ve bunun mekanizması henüz yoktur. İkinci sırada yaratırsan ya yanlış numarayı alır ya da kernel’i çökertir. Boot’ta sıranın tasarımın kendisi olduğu en net örneklerden biri.',
    },
    duration: 5800,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp'],
    console: ['pid 1 created (kernel_init)'],
    signals: [
      { route: ['cpuBsp', 'ram'], color: KERNEL, label: 'PID 1', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-pid0-2',
    phase: 'os',
    title: { en: 'PID 2, and the Thread That Becomes Idle', tr: 'PID 2 ve Idle’a Dönüşen Thread' },
    signal: 'kthreadd / cpu_startup_entry',
    description: {
      en: "Now that PID 1 has its number, the manager of kernel threads is created as PID 2 — every internal worker thread will be its child. Then the thread that has been executing this entire boot does something quietly remarkable: it becomes the idle task, PID 0, the thing that runs when there is nothing to run. The code that started the machine ends up as the code that does nothing.",
      tr: 'PID 1 numarasını aldığına göre, kernel thread’lerinin yöneticisi PID 2 olarak yaratılır — her dahili işçi thread onun çocuğu olacaktır. Sonra bu boot’un tamamını yürütmüş olan thread sessizce dikkat çekici bir şey yapar: idle task’a, PID 0’a dönüşür; yani çalışacak hiçbir şey olmadığında çalışan şeye. Makineyi başlatan kod, hiçbir şey yapmayan kod olarak son bulur.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: ['pid 2 created (kthreadd)', 'boot thread → idle task (pid 0)'],
    signals: [{ route: ['cpuBsp', 'cpuAp'], color: LOGIC, particles: 8, spread: 0.55 }],
  },

  // --- SMP and drivers -------------------------------------------------------
  {
    id: 'kernel-smp',
    phase: 'os',
    title: { en: 'smp_init() — Waking the Other Cores', tr: 'smp_init() — Diğer Çekirdekleri Uyandırmak' },
    signal: 'smp_init()',
    source: 'kernel/smp.c:1025',
    description: {
      en: 'Every core except one has been asleep since the firmware parked it, hours of CPU time ago in machine terms. The kernel now sends each a wake-up signal, and each starts executing at the same shared label the boot processor passed through long ago — which is exactly why that label was written to be shared. Sixteen cores go from one running to sixteen, and the scheduler suddenly has somewhere to put things.',
      tr: 'Biri hariç her çekirdek, firmware onu park ettiğinden beri uyuyor — makine ölçeğinde saatlerce CPU zamanı önce. Kernel şimdi her birine bir uyandırma sinyali gönderir ve her biri, boot işlemcisinin çok önce geçtiği aynı ortak etiketten çalışmaya başlar — o etiketin paylaşılacak şekilde yazılmış olmasının sebebi tam olarak budur. On altı çekirdek birden on altıya çıkar ve scheduler’ın birdenbire bir şeyleri koyacak yeri olur.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'cpuAp'],
    console: [
      '[    0.398] smpboot: CPU0: 13th Gen Intel(R) Core(TM) i7-13700K',
      '[    0.412] smp: Bringing up secondary CPUs ...',
      '[    0.487] smp: Brought up 1 node, 16 CPUs',
    ],
    signals: [
      { route: ['cpuBsp', 'cpuAp'], color: KERNEL, label: 'SIPI', particles: 18, spread: 0.75 },
      { route: ['cpuAp', 'cpuCache'], color: KERNEL, particles: 10, delay: 0.4, spread: 0.5 },
    ],
  },
  {
    id: 'kernel-initcalls',
    phase: 'os',
    title: { en: 'do_initcalls() — Every Driver, In Order', tr: 'do_initcalls() — Her Sürücü, Sırayla' },
    signal: 'do_initcalls()',
    source: 'init/main.c:1412',
    description: {
      en: 'Thousands of drivers are compiled into the kernel, and each registered a startup function at build time by placing a pointer in a special section. Those pointers are grouped into eight levels, and this walks them level by level — because a disk driver is useless before the PCI bus it hangs off has been probed. This single call is where most of the visible boot log comes from, and where most of the boot time goes.',
      tr: 'Kernel’e binlerce sürücü derlenmiştir ve her biri derleme anında özel bir bölüme pointer koyarak bir başlatma fonksiyonu kaydetmiştir. Bu pointer’lar sekiz seviyeye ayrılmıştır ve bu adım onları seviye seviye yürür — çünkü bir disk sürücüsü, asılı olduğu PCI veriyolu taranmadan işe yaramaz. Görünen boot günlüğünün çoğunun geldiği ve boot süresinin çoğunun gittiği yer bu tek çağrıdır.',
    },
    duration: 6000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['chipset', 'm2', 'pcie', 'ram'],
    console: [
      '[    0.612] PCI: Using ACPI for IRQ routing',
      '[    0.884] nvme nvme0: pci function 0000:01:00.0',
      '[    0.901] nvme nvme0: 8/0/0 default/read/poll queues',
      '[    0.947] i915 0000:00:02.0: [drm] Found ALDERLAKE_P',
    ],
    signals: [
      { route: ['chipset', 'pcie'], color: DATA, label: 'PCI probe', particles: 12, spread: 0.6 },
      { route: ['chipset', 'm2'], color: DATA, label: 'nvme', particles: 12, delay: 0.3, spread: 0.6 },
    ],
  },
  {
    id: 'kernel-initramfs',
    phase: 'os',
    title: { en: 'The initramfs Is Unpacked', tr: 'initramfs Açılıyor' },
    signal: 'wait_for_initramfs()',
    description: {
      en: "The archive GRUB loaded alongside the kernel is expanded into the empty root created earlier, and suddenly / has files in it — a small but complete userspace living entirely in RAM. This exists to solve a circular problem: the driver needed to read the root disk might itself live on the root disk. The initramfs carries whatever is needed to reach the real root, and nothing more.",
      tr: 'GRUB’ın kernel’in yanında yüklediği arşiv, daha önce oluşturulan boş kökün içine açılır ve birdenbire / içinde dosyalar olur — tamamen RAM’de yaşayan küçük ama eksiksiz bir userspace. Bu, dairesel bir sorunu çözmek için vardır: kök diski okumak için gereken sürücünün kendisi kök diskte olabilir. initramfs, gerçek köke ulaşmak için ne gerekiyorsa onu taşır, fazlasını değil.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'm2'],
    console: [
      '[    1.021] Unpacking initramfs...',
      '[    1.198] Freeing initrd memory: 42184K',
      '[    1.204] /dev/console opened',
    ],
    signals: [
      { route: ['ram', 'm2'], color: DATA, label: 'initramfs', particles: 12, spread: 0.65 },
    ],
  },

  // --- Handing over ----------------------------------------------------------
  {
    id: 'kernel-free-initmem',
    phase: 'os',
    title: { en: 'free_initmem() — Burning the Scaffolding', tr: 'free_initmem() — İskeleyi Yakmak' },
    signal: 'free_initmem()',
    source: 'arch/x86/mm/init.c:973',
    description: {
      en: 'Every function used only during boot was marked at compile time and gathered into one contiguous region. None of them will ever run again — you cannot boot a machine twice — so the kernel hands that entire region back to the allocator as free memory. It is a rare piece of software that deletes a part of itself once it is done starting, and the reclaimed megabytes are the reason it bothers.',
      tr: 'Yalnızca boot sırasında kullanılan her fonksiyon derleme anında işaretlenmiş ve tek bir bitişik bölgede toplanmıştır. Hiçbiri bir daha çalışmayacaktır — bir makineyi iki kez boot edemezsin — bu yüzden kernel o bölgenin tamamını boş bellek olarak ayırıcıya geri verir. Başlamayı bitirdiğinde kendi bir parçasını silen ender bir yazılım parçasıdır ve bunu geri kazanılan megabaytlar için yapar.',
    },
    duration: 5200,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['[    1.318] Freeing unused kernel image (initmem) memory: 2716K', '[    1.322] Write protecting the kernel read-only data: 26624k'],
    signals: [{ route: ['cpuBsp', 'ram'], color: KERNEL, particles: 10, spread: 0.6 }],
  },
  {
    id: 'kernel-init-search',
    phase: 'os',
    title: { en: 'Looking for Something to Run', tr: 'Çalıştıracak Bir Şey Aramak' },
    signal: '/init → /sbin/init → /bin/sh',
    description: {
      en: 'The kernel now needs a program to hand the machine to, and it tries candidates in a fixed order: the initramfs entry point first, then whatever init= on the command line named, then a list of traditional locations, and finally a plain shell as a last resort for a broken system. If every one fails it gives up with a message telling you exactly which option to pass — the kernel cannot continue without a first process.',
      tr: 'Kernel artık makineyi devredeceği bir programa ihtiyaç duyar ve adayları sabit bir sırayla dener: önce initramfs giriş noktası, sonra komut satırındaki init= neyi işaret ediyorsa o, sonra geleneksel konumların listesi ve en son çare olarak bozuk bir sistem için düz bir shell. Hepsi başarısız olursa, hangi seçeneği geçmen gerektiğini söyleyen bir mesajla pes eder — kernel ilk süreç olmadan devam edemez.',
    },
    duration: 5400,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['ram'],
    console: ['[    1.334] Run /init as init process'],
    signals: [{ route: ['ram', 'cpuBsp'], color: DATA, particles: 8, spread: 0.5 }],
  },
  {
    id: 'kernel-execve',
    phase: 'os',
    title: { en: 'kernel_execve() — sysretq to Userspace', tr: 'kernel_execve() — sysretq ile Userspace’e' },
    signal: 'kernel_execve()',
    source: 'fs/exec.c:1879',
    description: {
      en: "The handover contains no jump. The ELF loader writes the program's entry point into a saved register frame on the stack — as ordinary a write as any other — and then every function returns normally back up the chain. The transfer happens because the syscall return path restores those modified registers, and one sysretq drops the CPU into ring 3. The kernel has not left; it has only stopped being the only thing running. It is one interrupt away, permanently.",
      tr: 'Devir bir jump içermez. ELF loader, programın giriş noktasını stack üzerindeki kayıtlı bir register çerçevesine yazar — herhangi bir yazma kadar sıradan bir işlem — ve ardından her fonksiyon zincirin yukarısına doğru normal biçimde döner. Geçiş, syscall dönüş yolunun o değiştirilmiş register’ları geri yüklemesiyle olur ve tek bir sysretq CPU’yu ring 3’e bırakır. Kernel gitmedi; yalnızca çalışan tek şey olmayı bıraktı. Kalıcı olarak bir kesme uzaklıkta.',
    },
    duration: 6000,
    view: 'coreboot',
    screen: 'boot',
    depth: 1,
    highlight: ['cpuBsp', 'ram'],
    console: [
      'load_elf_binary: /init',
      'start_thread_common: regs->ip = 0x7f2c00001040',
      'swapgs ; sysretq  → ring 3',
    ],
    signals: [
      { route: ['cpuBsp', 'ram'], color: KERNEL, label: 'sysretq', particles: 16, spread: 0.7 },
    ],
  },
];
