import type { BootStep } from '../types';
import { RAIL_COLORS } from './constants';

/**
 * From systemd re-executing itself on the real root to multi-user.target.
 *
 * The reader is assumed not to be a systemd administrator, so the same rule as
 * the kernel chain applies: plain language first, the term second, and every
 * card answers why a step happens where it does.
 *
 * Two things make this section read differently from everything before it, and
 * the cards have to say so out loud. First, the order is not the order of the
 * code — it is a graph declared in unit files, and systemd only walks it.
 * Second, systemd's entire reason for existing is that it starts everything it
 * can at once; a chain drawn as a single line would misrepresent it, which is
 * why several cards fire simultaneous signals rather than staggered ones.
 *
 * Source paths point at ~/Projects/systemd (v262~devel). Function cards cite a
 * definition with a line number; target and service cards cite the unit file
 * with no line, because the whole file is the subject.
 */
const KERNEL = RAIL_COLORS.kernel;
const DATA = RAIL_COLORS.data;
const LOGIC = RAIL_COLORS.logic;

export const SYSTEMD_SEQUENCE_STEPS: BootStep[] = [
  // --- PID 1 gets on its feet ------------------------------------------------
  {
    id: 'systemd-run',
    phase: 'os',
    title: { en: 'run_systemd() — Starting for Real', tr: 'run_systemd() — Gerçekten Başlıyor' },
    signal: 'run_systemd()',
    source: 'src/core/main.c:3539',
    description: {
      en: 'The binary that just replaced itself begins here. Its main function is only a few lines — it checks whether it was invoked under another name and then calls this, which is where the actual work lives. The first thing it records is a pair of timestamps, one for how long the kernel took and one starting now, which is where the numbers in systemd-analyze come from.',
      tr: 'Az önce kendi yerine geçen ikili buradan başlar. main fonksiyonu yalnızca birkaç satırdır — başka bir adla çağrılıp çağrılmadığına bakar ve sonra asıl işin yaşadığı burayı çağırır. İlk kaydettiği şey bir çift zaman damgasıdır: biri kernel’in ne kadar sürdüğü, diğeri şimdi başlayan. systemd-analyze çıktısındaki sayılar buradan gelir.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram'],
    console: ['systemd[1]: systemd 262 running in system mode.'],
    signals: [{ route: ['m2', 'cpu'], color: KERNEL, particles: 10, spread: 0.55 }],
  },
  {
    id: 'systemd-pid1-branch',
    phase: 'os',
    title: { en: 'Am I PID 1?', tr: 'PID 1 miyim?' },
    signal: 'getpid_cached() == 1',
    description: {
      en: 'The same binary runs in two very different roles: as the system manager owning the whole machine, and as a per-user manager owning one login session. So it asks which one it is, and the answer changes almost everything that follows. As PID 1 it clears the inherited file-creation mask, because a mask set by whoever started it would silently affect the permissions of every file the system creates afterwards.',
      tr: 'Aynı ikili çok farklı iki rolde çalışır: tüm makinenin sahibi olan sistem yöneticisi ve tek bir oturumun sahibi olan kullanıcı yöneticisi. Bu yüzden hangisi olduğunu sorar ve cevap sonrasındaki neredeyse her şeyi değiştirir. PID 1 olarak miras aldığı dosya oluşturma maskesini temizler; çünkü onu başlatan her kimse tarafından kurulmuş bir maske, sistemin sonradan oluşturduğu her dosyanın izinlerini sessizce etkilerdi.',
    },
    duration: 4800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu'],
    console: ['systemd[1]: Running in system mode.', 'umask(0)'],
    signals: [],
  },
  {
    id: 'systemd-early-log',
    phase: 'os',
    title: { en: 'Nowhere to Write Logs Yet', tr: 'Henüz Log Yazacak Yer Yok' },
    signal: 'log_set_prohibit_ipc()',
    description: {
      en: 'systemd wants to log what it is doing, but the service that collects logs is one it has not started yet — and will not, for another few hundred lines. Worse, trying to reach it would block. So logging over the message bus is explicitly forbidden for now and everything goes to the kernel ring buffer instead, the same place kernel messages went. It is the only writable destination that certainly exists.',
      tr: 'systemd ne yaptığını loglamak ister, ama logları toplayan servis henüz başlatmadığı bir servistir — ve birkaç yüz satır daha başlatmayacaktır. Dahası, ona ulaşmayı denemek bloklanmaya yol açardı. Bu yüzden mesaj veriyolu üzerinden loglama şimdilik açıkça yasaklanır ve her şey bunun yerine kernel ring buffer’ına gider; kernel mesajlarının gittiği yerin aynısına. Kesinlikle var olduğu bilinen tek yazılabilir hedef odur.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram'],
    console: ['log target: kmsg'],
    signals: [{ route: ['cpu', 'ram'], color: LOGIC, label: 'kmsg', particles: 8, spread: 0.5 }],
  },
  {
    id: 'systemd-security',
    phase: 'os',
    title: { en: 'Loading the Security Policy', tr: 'Güvenlik Politikasını Yüklemek' },
    signal: 'initialize_security()',
    source: 'src/core/main.c:3175',
    description: {
      en: 'On a system using mandatory access control, a policy decides which process may touch which file — and unlike ordinary permissions, not even root can override it. That policy has to be loaded before any service starts, because a service started without it would be running unconfined. Loading it can require systemd to re-execute itself so the new rules apply to PID 1 too.',
      tr: 'Zorunlu erişim denetimi kullanan bir sistemde, hangi sürecin hangi dosyaya dokunabileceğine bir politika karar verir — ve sıradan izinlerin aksine root bile onu geçersiz kılamaz. Bu politika herhangi bir servis başlamadan önce yüklenmelidir, çünkü onsuz başlatılan bir servis kısıtlanmamış çalışıyor olurdu. Yüklemek, yeni kuralların PID 1’e de uygulanması için systemd’nin kendini yeniden çalıştırmasını gerektirebilir.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'm2'],
    console: ['systemd[1]: Successfully loaded SELinux policy in 41.2ms.'],
    signals: [{ route: ['m2', 'cpu'], color: DATA, label: 'policy', particles: 9, spread: 0.55 }],
  },
  {
    id: 'systemd-clock',
    phase: 'os',
    title: { en: 'Is the Clock Believable?', tr: 'Saat İnandırıcı mı?' },
    signal: 'clock_apply_epoch()',
    description: {
      en: 'If the battery on the board is dead the hardware clock may report a date years in the past, and a system that believes it will reject every TLS certificate it sees as not yet valid. So systemd compares the clock against the build date of its own binary — a date it knows cannot be in the future — and if the clock is earlier, it drags it forward. Not correct, but no longer absurd.',
      tr: 'Karttaki pil bittiyse donanım saati yıllar öncesini bildirebilir ve buna inanan bir sistem gördüğü her TLS sertifikasını henüz geçerli değil diye reddeder. Bu yüzden systemd saati kendi ikilisinin derlenme tarihiyle karşılaştırır — gelecekte olamayacağını bildiği bir tarih — ve saat daha erkendeyse onu ileri sürükler. Doğru değil, ama artık saçma da değil.',
    },
    duration: 4800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset'],
    console: ['systemd[1]: System time before build time, advancing clock.'],
    signals: [{ route: ['chipset', 'cpu'], color: LOGIC, particles: 7, spread: 0.5 }],
  },
  {
    id: 'systemd-environment',
    phase: 'os',
    title: { en: 'A Sane Environment', tr: 'Aklı Başında Bir Ortam' },
    signal: 'fixup_environment()',
    source: 'src/core/main.c:1702',
    description: {
      en: 'Every process inherits a set of environment variables from its parent, but PID 1 has no parent worth inheriting from — the kernel handed it almost nothing. So systemd fills in the basics itself: a terminal type read from the kernel command line, a home directory, a search path. It also points its own standard input, output and error at the null device, so that a stray write from any code it runs cannot land somewhere unexpected.',
      tr: 'Her süreç ebeveyninden bir dizi ortam değişkeni miras alır, ama PID 1’in miras alınmaya değer bir ebeveyni yoktur — kernel ona neredeyse hiçbir şey vermedi. Bu yüzden systemd temelleri kendisi doldurur: kernel komut satırından okunan bir terminal tipi, bir ev dizini, bir arama yolu. Ayrıca kendi standart girdi, çıktı ve hata akışlarını null aygıtına yöneltir; böylece çalıştırdığı herhangi bir koddan gelen başıboş bir yazma beklenmedik bir yere düşemez.',
    },
    duration: 4800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu'],
    console: ['TERM=linux  HOME=/  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'],
    signals: [],
  },
  {
    id: 'systemd-mount-setup',
    phase: 'os',
    title: { en: 'mount_setup() — The Filesystems Nobody Configures', tr: 'mount_setup() — Kimsenin Yapılandırmadığı Dosya Sistemleri' },
    signal: 'mount_setup()',
    source: 'src/shared/mount-setup.c:477',
    description: {
      en: 'A handful of filesystems are not storage at all — they are windows into the kernel. Reading a file under one of them runs kernel code and returns the answer as text. systemd mounts them itself rather than waiting for the fstab machinery, because it needs them immediately: process information, device attributes, its own runtime directory, and the control-group hierarchy it will use to keep track of every service it starts.',
      tr: 'Bir avuç dosya sistemi aslında depolama değildir — kernel’e açılan pencerelerdir. Onlardan birinin altındaki bir dosyayı okumak kernel kodu çalıştırır ve cevabı metin olarak döndürür. systemd bunları fstab mekanizmasını beklemek yerine kendisi mount eder, çünkü onlara hemen ihtiyacı vardır: süreç bilgisi, aygıt öznitelikleri, kendi çalışma dizini ve başlattığı her servisi takip etmek için kullanacağı control group hiyerarşisi.',
    },
    duration: 5600,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram', 'chipset'],
    console: ['mounting /proc /sys /dev /run', 'cgroup2 on /sys/fs/cgroup'],
    signals: [
      { route: ['cpu', 'ram'], color: KERNEL, label: '/proc /sys', particles: 10, spread: 0.5 },
      { route: ['cpu', 'chipset'], color: KERNEL, label: 'cgroup2', particles: 10, delay: 0, spread: 0.5 },
    ],
  },
  {
    id: 'systemd-efi-lock',
    phase: 'os',
    title: { en: 'Locking a Door Behind It', tr: 'Arkasından Bir Kapıyı Kilitlemek' },
    signal: 'lock_down_efi_variables()',
    source: 'src/core/efi-random.c:12',
    description: {
      en: 'The firmware left a random seed in an EFI variable for the kernel to use, and that variable is now readable through a filesystem that was just mounted. Leaving it readable would let any process with access recover entropy the system is still using. So systemd makes it immutable, closing the door on a value that has already served its purpose.',
      tr: 'Firmware, kernel’in kullanması için bir EFI değişkeninde rastgele bir tohum bıraktı ve o değişken az önce mount edilen bir dosya sistemi üzerinden okunabilir durumda. Okunabilir bırakmak, erişimi olan herhangi bir sürecin sistemin hâlâ kullandığı entropiyi geri elde etmesine izin verirdi. Bu yüzden systemd onu değiştirilemez yapar ve amacını çoktan yerine getirmiş bir değerin kapısını kapatır.',
    },
    duration: 4600,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['spiFlash', 'cpu'],
    console: ['EFI system token locked'],
    signals: [{ route: ['spiFlash', 'cpu'], color: LOGIC, particles: 7, spread: 0.5 }],
  },

  // --- Configuration ---------------------------------------------------------
  {
    id: 'systemd-config',
    phase: 'os',
    title: { en: 'Reading Its Own Configuration', tr: 'Kendi Yapılandırmasını Okumak' },
    signal: 'parse_configuration()',
    source: 'src/core/main.c:191',
    description: {
      en: 'Before it manages anything else, systemd reads the settings that govern its own behaviour: default timeouts, resource limits handed to every service, what to do when a watchdog expires. These are defaults inherited by everything it will start, so they have to be settled before the first unit is even loaded.',
      tr: 'Başka bir şeyi yönetmeden önce systemd kendi davranışını belirleyen ayarları okur: varsayılan zaman aşımları, her servise verilen kaynak sınırları, bir watchdog dolduğunda ne yapılacağı. Bunlar başlatacağı her şeyin miras alacağı varsayılanlardır, dolayısıyla ilk unit yüklenmeden bile önce karara bağlanmalıdır.',
    },
    duration: 4800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'm2'],
    console: ['reading /etc/systemd/system.conf'],
    signals: [{ route: ['m2', 'cpu'], color: DATA, particles: 8, spread: 0.5 }],
  },
  {
    id: 'systemd-parse-argv',
    phase: 'os',
    title: { en: 'The Note From the initramfs', tr: 'initramfs’ten Gelen Not' },
    signal: '--switched-root --deserialize',
    source: 'src/core/main.c:1042',
    description: {
      en: 'The arguments handed over during the pivot are read here, and one of them is a file descriptor number. Behind it sits everything the previous instance knew — which units it had started, which sockets it was holding open, how far it had got. This is what makes the handover seamless rather than a restart: the state is not rebuilt, it is inherited, and services already running are simply adopted.',
      tr: 'Pivot sırasında devredilen argümanlar burada okunur ve bunlardan biri bir file descriptor numarasıdır. Arkasında bir önceki örneğin bildiği her şey durur — hangi unit’leri başlattığı, hangi soketleri açık tuttuğu, nereye kadar geldiği. Devrin bir yeniden başlatma değil de kesintisiz olmasını sağlayan budur: durum yeniden kurulmaz, miras alınır ve halihazırda çalışan servisler basitçe sahiplenilir.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'cpu'],
    console: ['systemd[1]: --switched-root --system --deserialize=27'],
    signals: [
      { route: ['ram', 'cpu'], color: DATA, label: 'serialized state', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'systemd-runtime',
    phase: 'os',
    title: { en: 'Giving the Machine an Identity', tr: 'Makineye Bir Kimlik Vermek' },
    signal: 'initialize_runtime()',
    source: 'src/core/main.c:2656',
    description: {
      en: 'A machine needs a few things to be true about itself before anything can rely on them: a unique identifier that survives reboots, a hostname, and a working loopback interface so that a program can talk to another program on the same host. None of these exist yet on a first boot, so systemd generates or configures them. The loopback matters more than it sounds: the message bus everything else uses runs over it.',
      tr: 'Bir makinenin, herhangi bir şey ona güvenmeden önce kendisi hakkında doğru olması gereken birkaç şeyi vardır: yeniden başlatmalardan sağ çıkan benzersiz bir tanımlayıcı, bir hostname ve bir programın aynı makinedeki başka bir programla konuşabilmesi için çalışan bir loopback arayüzü. İlk boot’ta bunların hiçbiri yoktur, bu yüzden systemd onları üretir ya da yapılandırır. Loopback kulağa geldiğinden önemlidir: diğer her şeyin kullandığı mesaj veriyolu onun üzerinden çalışır.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset'],
    console: ['systemd[1]: Set hostname to <workstation>.', 'machine-id: 8f2c1e...'],
    signals: [{ route: ['cpu', 'chipset'], color: LOGIC, particles: 8, spread: 0.5 }],
  },

  // --- The manager -----------------------------------------------------------
  {
    id: 'systemd-manager-new',
    phase: 'os',
    title: { en: 'manager_new() — Something to Wait On', tr: 'manager_new() — Bekleyecek Bir Şey' },
    signal: 'manager_new()',
    source: 'src/core/manager.c:922',
    description: {
      en: 'systemd spends its life waiting for things to happen, so the first object it builds is the thing that lets it wait on many sources at once without a thread for each: a single kernel-managed set of file descriptors it can block on. Signals, timers, process exits and socket connections are all converted into readable descriptors and dropped into it. From here on the program is a loop around that one wait.',
      tr: 'systemd ömrünü bir şeylerin olmasını bekleyerek geçirir, bu yüzden kurduğu ilk nesne, her biri için ayrı bir thread olmadan aynı anda birçok kaynağı beklemesini sağlayan şeydir: bloklanabileceği, kernel tarafından yönetilen tek bir file descriptor kümesi. Sinyaller, zamanlayıcılar, süreç çıkışları ve soket bağlantıları hep okunabilir descriptor’lara çevrilip içine bırakılır. Buradan sonrası, o tek beklemenin etrafındaki bir döngüdür.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram'],
    console: ['manager: epoll and signalfd ready'],
    signals: [{ route: ['cpu', 'ram'], color: KERNEL, particles: 9, spread: 0.5 }],
  },
  {
    id: 'systemd-lookup-paths',
    phase: 'os',
    title: { en: 'Three Directories, In Order', tr: 'Üç Dizin, Sırayla' },
    signal: 'lookup_paths_init_or_warn()',
    source: 'src/libsystemd/sd-path/path-lookup.c:726',
    description: {
      en: 'Descriptions of services live in three places and the order is the whole design. What the distribution ships goes in one directory, what is generated at runtime in another, and what the administrator writes in a third — and the administrator wins. That is why editing a service never means touching a file a package update will overwrite: you place your version in the directory that outranks it.',
      tr: 'Servis tarifleri üç yerde yaşar ve sıra tasarımın kendisidir. Dağıtımın verdiği bir dizine, çalışma anında üretilen bir diğerine, yöneticinin yazdığı üçüncüsüne gider — ve yönetici kazanır. Bir servisi düzenlemenin, paket güncellemesinin üzerine yazacağı bir dosyaya dokunmak anlamına gelmemesinin sebebi budur: kendi sürümünüzü, ondan üstün olan dizine koyarsınız.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'cpu'],
    console: [
      '/etc/systemd/system      (administrator)',
      '/run/systemd/system      (runtime)',
      '/usr/lib/systemd/system  (distribution)',
    ],
    signals: [{ route: ['m2', 'cpu'], color: DATA, label: 'unit paths', particles: 10, spread: 0.55 }],
  },
  {
    id: 'systemd-generators',
    phase: 'os',
    title: { en: 'Turning Old Config Into Units', tr: 'Eski Yapılandırmayı Unit’e Çevirmek' },
    signal: 'manager_run_environment_generators()',
    source: 'src/core/manager.c:4291',
    description: {
      en: 'systemd only understands units, but a machine is full of configuration written long before systemd existed. Rather than demand everyone convert, it runs a set of small programs that translate: the classic filesystem table becomes mount units, a swap line becomes a swap unit, kernel command-line options become overrides. They run before anything is loaded, and what they write lands in the runtime directory — which is why those units exist but appear in no file you can find.',
      tr: 'systemd yalnızca unit anlar, ama bir makine systemd var olmadan çok önce yazılmış yapılandırmayla doludur. Herkesten dönüştürmesini istemek yerine, çeviri yapan küçük programlar çalıştırır: klasik dosya sistemi tablosu mount unit’lerine, bir swap satırı swap unit’ine, kernel komut satırı seçenekleri geçersiz kılmalara dönüşür. Hiçbir şey yüklenmeden önce çalışırlar ve yazdıkları çalışma dizinine düşer — o unit’lerin var olup da bulabileceğiniz hiçbir dosyada görünmemesinin sebebi budur.',
    },
    duration: 5600,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'cpu', 'ram'],
    console: [
      'systemd-fstab-generator: /etc/fstab -> home.mount',
      'systemd-gpt-auto-generator: found ESP, generating boot.mount',
    ],
    signals: [
      { route: ['m2', 'ram'], color: DATA, label: 'generators', particles: 11, spread: 0.6 },
    ],
  },
  {
    id: 'systemd-enumerate',
    phase: 'os',
    title: { en: 'Building the Dependency Graph', tr: 'Bağımlılık Grafiğini Kurmak' },
    signal: 'manager_startup()',
    source: 'src/core/manager.c:2142',
    description: {
      en: 'Every unit file on the machine is read and turned into a node, and every ordering line in them becomes an edge. This is the moment the boot stops being a sequence anyone wrote down and becomes a graph nobody did — assembled from thousands of separate declarations, none of which knows about the others. Nothing has started yet; systemd is still only working out what depends on what.',
      tr: 'Makinedeki her unit dosyası okunup bir düğüme çevrilir ve içlerindeki her sıralama satırı bir kenara dönüşür. Boot’un, kimsenin yazdığı bir dizi olmaktan çıkıp kimsenin yazmadığı bir grafiğe dönüştüğü an budur — hiçbiri diğerlerinden haberdar olmayan binlerce ayrı bildirimden derlenmiş bir grafik. Henüz hiçbir şey başlamadı; systemd hâlâ yalnızca neyin neye bağlı olduğunu çıkarıyor.',
    },
    duration: 5800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram', 'm2'],
    console: ['systemd[1]: Loaded 412 unit files'],
    signals: [
      { route: ['m2', 'ram'], color: DATA, particles: 12, spread: 0.6 },
      { route: ['ram', 'cpu'], color: KERNEL, label: 'unit graph', particles: 12, delay: 0, spread: 0.6 },
    ],
  },
  {
    id: 'systemd-coldplug',
    phase: 'os',
    title: { en: 'Catching Up With Reality', tr: 'Gerçekle Arayı Kapatmak' },
    signal: 'manager_coldplug()',
    source: 'src/core/manager.c:1858',
    description: {
      en: 'The graph systemd just built describes what should be true; the machine already has opinions of its own. Some filesystems are mounted, some devices exist, some services inherited from the initramfs are running. So each unit is walked and asked to look at the world and record what it actually finds, rather than assuming it starts from nothing. Skip this and systemd would try to mount a filesystem that is already mounted.',
      tr: 'systemd’nin az önce kurduğu grafik neyin doğru olması gerektiğini tarif eder; makinenin ise kendi görüşleri zaten vardır. Bazı dosya sistemleri mount edilmiş, bazı aygıtlar mevcut, initramfs’ten miras kalan bazı servisler çalışıyordur. Bu yüzden her unit tek tek dolaşılır ve hiçbir şeyden başladığını varsaymak yerine dünyaya bakıp gerçekte ne bulduğunu kaydetmesi istenir. Bu atlanırsa systemd zaten mount edilmiş bir dosya sistemini mount etmeye kalkardı.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset', 'm2'],
    console: ['coldplug: 3 mounts, 1 service adopted from initrd'],
    signals: [
      { route: ['chipset', 'cpu'], color: LOGIC, particles: 9, spread: 0.55 },
      { route: ['m2', 'cpu'], color: LOGIC, particles: 9, delay: 0, spread: 0.55 },
    ],
  },

  // --- Choosing the goal -----------------------------------------------------
  {
    id: 'systemd-default-target',
    phase: 'os',
    title: { en: 'What Is This Machine For?', tr: 'Bu Makine Ne İçin?' },
    signal: 'default.target',
    source: 'units/graphical.target',
    description: {
      en: 'systemd does not start services; it is given one goal and works out everything that must be true to reach it. The goal is a symbolic link, and where it points is the difference between a server and a desktop: a machine that stops at a text console, or one that carries on to a graphical login. Changing what a machine boots into is changing where that one link points.',
      tr: 'systemd servis başlatmaz; ona tek bir hedef verilir ve ona ulaşmak için doğru olması gereken her şeyi kendisi çıkarır. Hedef bir sembolik bağdır ve nereyi gösterdiği bir sunucu ile bir masaüstü arasındaki farktır: metin konsolunda duran bir makine mi, yoksa grafik girişe kadar devam eden bir makine mi. Bir makinenin neye boot edeceğini değiştirmek, o tek bağın gösterdiği yeri değiştirmektir.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'm2'],
    console: ['default.target -> /usr/lib/systemd/system/graphical.target'],
    signals: [{ route: ['m2', 'cpu'], color: KERNEL, label: 'default.target', particles: 10, spread: 0.55 }],
  },
  {
    id: 'systemd-main-loop',
    phase: 'os',
    title: { en: 'manager_loop() — No Longer a Program', tr: 'manager_loop() — Artık Bir Program Değil' },
    signal: 'manager_loop()',
    source: 'src/core/manager.c:3595',
    description: {
      en: 'Everything up to this line ran top to bottom, and nothing after it does. systemd now blocks on its wait, and each thing that wakes it — a process exiting, a device appearing, a timer firing — is matched against the graph to see what has become possible. Reading the rest of this section as a sequence is a mistake the boot log encourages and the code does not support: what follows is order emerging from dependencies, not from lines.',
      tr: 'Bu satıra kadarki her şey yukarıdan aşağı çalıştı, sonrasındaki hiçbir şey öyle çalışmıyor. systemd artık beklemesinde bloklanır ve onu uyandıran her şey — çıkan bir süreç, beliren bir aygıt, dolan bir zamanlayıcı — neyin mümkün hâle geldiğini görmek için grafiğe karşı denetlenir. Bu bölümün geri kalanını bir dizi olarak okumak, boot günlüğünün teşvik ettiği ama kodun desteklemediği bir hatadır: bundan sonrası satırlardan değil, bağımlılıklardan doğan bir sıradır.',
    },
    duration: 5800,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram', 'chipset'],
    console: ['systemd[1]: Startup finished in 1.412s (kernel) + 2.907s (initrd)...'],
    signals: [
      { route: ['cpu', 'chipset'], color: KERNEL, particles: 8, spread: 0.5 },
      { route: ['cpu', 'ram'], color: KERNEL, particles: 8, delay: 0, spread: 0.5 },
      { route: ['cpu', 'm2'], color: KERNEL, particles: 8, delay: 0, spread: 0.5 },
    ],
  },

  // --- sysinit.target --------------------------------------------------------
  {
    id: 'systemd-local-fs',
    phase: 'os',
    title: { en: 'The Rest of the Filesystems', tr: 'Dosya Sistemlerinin Geri Kalanı' },
    signal: 'local-fs.target',
    source: 'units/local-fs.target',
    description: {
      en: 'The root was mounted back in the initramfs, but a typical machine has more: a separate home, a boot partition, swap. These come from the mount units the generators produced earlier, and they are grouped under a single milestone so that anything needing a complete filesystem tree can wait for one name instead of listing every mount.',
      tr: 'Kök initramfs’te mount edilmişti, ama tipik bir makinede daha fazlası vardır: ayrı bir home, bir boot bölümü, swap. Bunlar generator’ların daha önce ürettiği mount unit’lerinden gelir ve tek bir kilometre taşı altında gruplanır; böylece eksiksiz bir dosya sistemi ağacına ihtiyaç duyan herhangi bir şey, her mount’u tek tek listelemek yerine tek bir adı bekleyebilir.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['m2', 'chipset'],
    console: [
      '[  OK  ] Mounted /boot.',
      '[  OK  ] Mounted /home.',
      '[  OK  ] Reached target Local File Systems.',
    ],
    signals: [
      { route: ['chipset', 'm2'], color: DATA, label: 'mounts', particles: 12, spread: 0.6 },
    ],
  },
  {
    id: 'systemd-journald',
    phase: 'os',
    title: { en: 'journald — The Logs Have Somewhere to Go', tr: 'journald — Loglar Gidecek Bir Yer Buldu' },
    signal: 'systemd-journald.service',
    source: 'units/systemd-journald.service.in',
    description: {
      en: 'The service that collects logs starts before almost everything else, and its unit file explicitly opts out of the default dependencies every other service gets — because those dependencies would themselves want to log. Once it is up, the messages systemd has been holding in the kernel buffer are drained into it, along with everything the kernel itself printed. This is why journalctl can show you the very first line of a boot.',
      tr: 'Logları toplayan servis neredeyse her şeyden önce başlar ve unit dosyası, diğer her servisin aldığı varsayılan bağımlılıklardan açıkça muaf tutar kendini — çünkü o bağımlılıklar da loglamak isterdi. Ayağa kalktığında systemd’nin kernel tamponunda tuttuğu mesajlar, kernel’in kendi bastıklarıyla birlikte içine boşaltılır. journalctl’in bir boot’un en ilk satırını gösterebilmesinin sebebi budur.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram', 'm2'],
    console: [
      '[  OK  ] Started Journal Service.',
      'systemd-journald[298]: Runtime Journal begun on /run/log/journal',
    ],
    signals: [
      { route: ['ram', 'm2'], color: DATA, label: 'journal', particles: 11, spread: 0.6 },
    ],
  },
  {
    id: 'systemd-udevd-real',
    phase: 'os',
    title: { en: 'udev, This Time From the Real Disk', tr: 'udev, Bu Sefer Gerçek Diskten' },
    signal: 'systemd-udevd.service',
    source: 'units/systemd-udevd.service.in',
    description: {
      en: 'The device manager ran once already, inside the initramfs, with only the handful of rules that fit in the archive. Now it starts again with the full rule set from the real root — thousands of rules covering hardware the initramfs had no reason to know about. Everything the machine has, rather than only what was needed to find the disk, gets named and made available.',
      tr: 'Aygıt yöneticisi bir kez zaten çalıştı, initramfs içinde, arşive sığan bir avuç kuralla. Şimdi gerçek kökten gelen tam kural kümesiyle yeniden başlar — initramfs’in bilmek için hiçbir sebebi olmayan donanımı kapsayan binlerce kural. Makinenin sahip olduğu her şey, yalnızca diski bulmak için gerekenler değil, adlandırılır ve kullanılabilir hâle gelir.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['chipset', 'pcie', 'm2'],
    console: [
      '[  OK  ] Started Rule-based Manager for Device Events and Files.',
      'systemd-udevd[312]: settle: 218 devices',
    ],
    signals: [
      { route: ['chipset', 'pcie'], color: DATA, particles: 10, spread: 0.55 },
      { route: ['chipset', 'm2'], color: DATA, particles: 10, delay: 0, spread: 0.55 },
    ],
  },
  {
    id: 'systemd-sysctl',
    phase: 'os',
    title: { en: 'Why sysctl Waits for modules-load', tr: 'sysctl Neden modules-load’u Bekler' },
    signal: 'systemd-sysctl.service',
    source: 'units/systemd-sysctl.service.in',
    description: {
      en: 'Kernel tuning knobs are files, and a file only exists once the code that owns it is loaded. Setting a network parameter before the network module is in memory would fail, not because the value is wrong but because the file is not there yet. So one unit file carries a single line declaring it must run after module loading — and that one line is the entire reason the order holds. Nobody wrote a script; two units simply agree.',
      tr: 'Kernel ayar düğmeleri birer dosyadır ve bir dosya, ancak sahibi olan kod yüklendiğinde var olur. Ağ modülü bellekte değilken bir ağ parametresi ayarlamak başarısız olurdu — değer yanlış olduğu için değil, dosya henüz orada olmadığı için. Bu yüzden bir unit dosyası, modül yüklemesinden sonra çalışması gerektiğini bildiren tek bir satır taşır ve sıranın tutmasının tüm sebebi o tek satırdır. Kimse bir betik yazmadı; iki unit yalnızca anlaştı.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram'],
    console: [
      '[  OK  ] Started Load Kernel Modules.',
      '[  OK  ] Started Apply Kernel Variables.',
    ],
    signals: [{ route: ['ram', 'cpu'], color: LOGIC, particles: 8, spread: 0.5 }],
  },
  {
    id: 'systemd-tmpfiles',
    phase: 'os',
    title: { en: 'Directories That Have to Be Recreated', tr: 'Her Seferinde Yeniden Kurulması Gereken Dizinler' },
    signal: 'systemd-tmpfiles-setup.service',
    source: 'units/systemd-tmpfiles-setup.service',
    description: {
      en: 'Some directories live in memory and therefore vanish on every reboot, yet services expect to find them with the right owner and permissions. Rather than have each service create its own, they are declared in text files and made in one pass. The random seed saved at last shutdown is also fed back to the kernel around here, so that a machine has usable entropy before anything asks for a key.',
      tr: 'Bazı dizinler bellekte yaşar ve dolayısıyla her yeniden başlatmada kaybolur; oysa servisler onları doğru sahip ve izinlerle bulmayı bekler. Her servisin kendisininkini oluşturması yerine, metin dosyalarında bildirilir ve tek geçişte oluşturulurlar. Son kapanışta kaydedilen rastgele tohum da bu civarda kernel’e geri verilir; böylece herhangi bir şey anahtar istemeden önce makinenin kullanılabilir entropisi olur.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['ram', 'm2'],
    console: [
      '[  OK  ] Started Create Volatile Files and Directories.',
      '[  OK  ] Started Load/Save Random Seed.',
    ],
    signals: [{ route: ['m2', 'ram'], color: DATA, particles: 9, spread: 0.55 }],
  },
  {
    id: 'systemd-sysinit',
    phase: 'os',
    title: { en: 'sysinit.target — The Machine Is Set Up', tr: 'sysinit.target — Makine Kuruldu' },
    signal: 'sysinit.target',
    source: 'units/sysinit.target',
    description: {
      en: 'A target starts nothing itself. It is a name that becomes true once everything grouped under it has finished, so that hundreds of other units can wait for one word instead of enumerating the lot. When this one is reached, the machine is set up but does nothing useful yet: filesystems mounted, devices named, logs flowing, kernel tuned.',
      tr: 'Bir target kendisi hiçbir şey başlatmaz. Altında gruplanan her şey bittiğinde doğru hâle gelen bir isimdir; böylece yüzlerce başka unit, hepsini tek tek saymak yerine tek bir kelimeyi bekleyebilir. Buna ulaşıldığında makine kurulmuştur ama henüz işe yarar bir şey yapmaz: dosya sistemleri mount edilmiş, aygıtlar adlandırılmış, loglar akıyor, kernel ayarlanmış.',
    },
    duration: 5000,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram', 'm2', 'chipset'],
    console: ['[  OK  ] Reached target System Initialization.'],
    signals: [
      { route: ['cpu', 'ram'], color: KERNEL, particles: 8, spread: 0.5 },
      { route: ['cpu', 'chipset'], color: KERNEL, particles: 8, delay: 0, spread: 0.5 },
    ],
  },

  // --- basic.target ----------------------------------------------------------
  {
    id: 'systemd-slices',
    phase: 'os',
    title: { en: 'Carving the Machine Into Slices', tr: 'Makineyi Dilimlere Ayırmak' },
    signal: 'slices.target',
    source: 'units/slices.target',
    description: {
      en: 'Every process systemd starts is placed in a group the kernel tracks, and those groups form a tree. The tree matters because limits apply to a branch rather than to one process: cap the branch holding user sessions and no single runaway program can starve the system services on the neighbouring branch. It also means systemd always knows exactly which processes belong to a service, even ones that tried to escape by forking away.',
      tr: 'systemd’nin başlattığı her süreç, kernel’in takip ettiği bir gruba yerleştirilir ve o gruplar bir ağaç oluşturur. Ağaç önemlidir çünkü sınırlar tek bir sürece değil bir dala uygulanır: kullanıcı oturumlarını tutan dalı sınırla, kaçak tek bir program komşu daldaki sistem servislerini aç bırakamasın. Ayrıca systemd’nin bir servise hangi süreçlerin ait olduğunu her zaman tam olarak bilmesi anlamına gelir — fork ederek kaçmayı denemiş olanları bile.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'ram'],
    console: ['[  OK  ] Created slice system.slice.', '[  OK  ] Created slice user.slice.'],
    signals: [{ route: ['cpu', 'ram'], color: LOGIC, label: 'cgroup tree', particles: 10, spread: 0.6 }],
  },
  {
    id: 'systemd-sockets',
    phase: 'os',
    title: { en: 'Opening Sockets Without Starting Services', tr: 'Servisi Başlatmadan Soketi Açmak' },
    signal: 'sockets.target',
    source: 'units/sockets.target',
    description: {
      en: 'Here systemd does something that removes most of the ordering problem entirely: it opens the listening sockets, but starts nothing behind them. A client can connect immediately and its request simply waits in the kernel queue; the service is launched on the first connection and never notices the delay. Because every service can be contacted from the moment its socket exists, almost nothing has to wait for anything else to finish starting.',
      tr: 'systemd burada sıralama sorununun çoğunu tamamen ortadan kaldıran bir şey yapar: dinleme soketlerini açar ama arkalarında hiçbir şey başlatmaz. Bir istemci hemen bağlanabilir ve isteği kernel kuyruğunda bekler; servis ilk bağlantıda başlatılır ve gecikmeyi hiç fark etmez. Her servise soketi var olduğu andan itibaren ulaşılabildiği için, neredeyse hiçbir şeyin bir başkasının başlamasını beklemesi gerekmez.',
    },
    duration: 5600,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset', 'ram'],
    console: [
      '[  OK  ] Listening on D-Bus System Message Bus Socket.',
      '[  OK  ] Listening on Journal Socket.',
      '[  OK  ] Reached target Basic System.',
    ],
    signals: [
      { route: ['cpu', 'chipset'], color: DATA, particles: 9, spread: 0.5 },
      { route: ['cpu', 'ram'], color: DATA, particles: 9, delay: 0, spread: 0.5 },
    ],
  },

  // --- multi-user.target -----------------------------------------------------
  {
    id: 'systemd-dbus-logind',
    phase: 'os',
    title: { en: 'D-Bus and logind', tr: 'D-Bus ve logind' },
    signal: 'systemd-logind.service',
    source: 'src/login/logind.c:1350',
    description: {
      en: 'Programs need a way to call each other that is not a file or a raw socket, and on Linux that is a message bus: one process routes named requests between all the others. logind is one of the first things to appear on it. Its job is to know who is logged in, at which physical screen and keyboard, and to hand out permission to touch the graphics and sound hardware accordingly — which is what makes it impossible for a remote login to grab the local display.',
      tr: 'Programların birbirini çağırmak için dosya ya da ham soket olmayan bir yola ihtiyacı vardır ve Linux’ta bu bir mesaj veriyoludur: bir süreç, adlandırılmış istekleri diğer hepsinin arasında yönlendirir. logind, üzerinde beliren ilk şeylerden biridir. İşi, kimin hangi fiziksel ekran ve klavyede oturum açtığını bilmek ve buna göre grafik ile ses donanımına dokunma izni dağıtmaktır — uzaktan bir oturumun yerel ekranı ele geçirmesini imkânsız kılan da budur.',
    },
    duration: 5600,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset', 'pcie'],
    console: [
      '[  OK  ] Started D-Bus System Message Bus.',
      '[  OK  ] Started User Login Management.',
      'systemd-logind[401]: New seat seat0.',
    ],
    signals: [
      { route: ['cpu', 'chipset'], color: KERNEL, label: 'D-Bus', particles: 10, spread: 0.55 },
      { route: ['chipset', 'pcie'], color: LOGIC, particles: 8, delay: 0, spread: 0.5 },
    ],
  },
  {
    id: 'systemd-user-sessions',
    phase: 'os',
    title: { en: 'Deleting One File Opens the Doors', tr: 'Tek Bir Dosyayı Silmek Kapıları Açıyor' },
    signal: 'systemd-user-sessions.service',
    source: 'units/systemd-user-sessions.service.in',
    description: {
      en: 'Throughout the boot a single file has existed whose mere presence makes every login attempt fail — the login programs check for it and refuse. It is there on purpose, so that nobody can log into a machine whose filesystems and network are still coming up. This service does nothing but delete it, and that deletion is the moment the machine becomes usable by a person.',
      tr: 'Boot boyunca, yalnızca var olması her giriş denemesini başarısız kılan tek bir dosya mevcuttu — giriş programları ona bakar ve reddeder. Bilerek oradadır; böylece dosya sistemleri ve ağı hâlâ ayağa kalkmakta olan bir makineye kimse giriş yapamaz. Bu servis onu silmekten başka bir şey yapmaz ve o silme, makinenin bir insan tarafından kullanılabilir hâle geldiği andır.',
    },
    duration: 5200,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'm2'],
    console: [
      '[  OK  ] Started Permit User Sessions.',
      'removed /run/nologin',
    ],
    signals: [{ route: ['cpu', 'm2'], color: LOGIC, particles: 8, spread: 0.5 }],
  },
  {
    id: 'systemd-multi-user',
    phase: 'os',
    title: { en: 'multi-user.target — A Working System', tr: 'multi-user.target — Çalışan Bir Sistem' },
    signal: 'multi-user.target',
    source: 'units/multi-user.target',
    description: {
      en: 'The text consoles are running, the network is configured, remote access works, and every background service a server would need is up. On a machine without a screen this is the end of the boot — nothing further is wanted. On a desktop it is the platform the graphical layer is about to be built on, and everything after this point is optional in a way nothing before it was.',
      tr: 'Metin konsolları çalışıyor, ağ yapılandırılmış, uzaktan erişim çalışır durumda ve bir sunucunun ihtiyaç duyacağı her arka plan servisi ayakta. Ekranı olmayan bir makinede boot’un sonu burasıdır — daha fazlası istenmez. Bir masaüstünde ise grafik katmanın üzerine kurulacağı zemindir ve bu noktadan sonraki her şey, öncesindeki hiçbir şeyin olmadığı bir anlamda isteğe bağlıdır.',
    },
    duration: 5400,
    view: 'board',
    screen: 'boot',
    depth: 1,
    highlight: ['cpu', 'chipset', 'm2', 'pcie'],
    console: [
      '[  OK  ] Started Network Manager.',
      '[  OK  ] Started OpenSSH server daemon.',
      '[  OK  ] Started Getty on tty1.',
      '[  OK  ] Reached target Multi-User System.',
    ],
    signals: [
      { route: ['cpu', 'chipset'], color: KERNEL, particles: 9, spread: 0.5 },
      { route: ['cpu', 'm2'], color: KERNEL, particles: 9, delay: 0, spread: 0.5 },
      { route: ['cpu', 'pcie'], color: KERNEL, particles: 9, delay: 0, spread: 0.5 },
    ],
  },
];
